Require Import Instructions.

Inductive i_type := RType | R4Type | IType | SType | BType | UType | JType.

Definition get_instruction_i_type (i : instruction) :=
  match i with
  | LUI_32I            => UType  | AUIPC_32I          => UType
  | JAL_32I            => JType  | JALR_32I           => IType
  | BEQ_32I            => BType  | BNE_32I            => BType
  | BLT_32I            => BType  | BGE_32I            => BType
  | BLTU_32I           => BType  | BGEU_32I           => BType
  | LB_32I             => IType  | LH_32I             => IType
  | LW_32I             => IType  | LBU_32I            => IType
  | LHU_32I            => IType  | SB_32I             => SType
  | SH_32I             => SType  | SW_32I             => SType
  | ADDI_32I           => IType  | SLTI_32I           => IType
  | SLTIU_32I          => IType  | XORI_32I           => IType
  | ORI_32I            => IType  | ANDI_32I           => IType
  | SLLI_32I           => IType  | SRLI_32I           => IType
  | SRAI_32I           => IType  | ADD_32I            => RType
  | SUB_32I            => RType  | SLL_32I            => RType
  | SLT_32I            => RType  | SLTU_32I           => RType
  | XOR_32I            => RType  | SRL_32I            => RType
  | SRA_32I            => RType  | OR_32I             => RType
  | AND_32I            => RType  | FENCE_32I          => IType
  | ECALL_32I          => IType  | EBREAK_32I         => IType
  | LUI_64I            => UType  | AUIPC_64I          => UType
  | JAL_64I            => JType  | JALR_64I           => IType
  | BEQ_64I            => BType  | BNE_64I            => BType
  | BLT_64I            => BType  | BGE_64I            => BType
  | BLTU_64I           => BType  | BGEU_64I           => BType
  | LB_64I             => IType  | LH_64I             => IType
  | LW_64I             => IType  | LBU_64I            => IType
  | LHU_64I            => IType  | SB_64I             => SType
  | SH_64I             => SType  | SW_64I             => SType
  | ADDI_64I           => IType  | SLTI_64I           => IType
  | SLTIU_64I          => IType  | XORI_64I           => IType
  | ORI_64I            => IType  | ANDI_64I           => IType
  | SLLI_64I           => IType  | SRLI_64I           => IType
  | SRAI_64I           => IType  | ADD_64I            => RType
  | SUB_64I            => RType  | SLL_64I            => RType
  | SLT_64I            => RType  | SLTU_64I           => RType
  | XOR_64I            => RType  | SRL_64I            => RType
  | SRA_64I            => RType  | OR_64I             => RType
  | AND_64I            => RType  | FENCE_64I          => IType
  | ECALL_64I          => IType  | EBREAK_64I         => IType
  | LWU_64I            => IType  | LD_64I             => IType
  | SD_64I             => SType  | ADDIW_64I          => IType
  | SLLIW_64I          => IType  | SRLIW_64I          => IType
  | SRAIW_64I          => IType  | ADDW_64I           => RType
  | SUBW_64I           => RType  | SLLW_64I           => RType
  | SRLW_64I           => RType  | SRAW_64I           => RType
  | FENCE_I_32Zifencei => IType  | FENCE_I_64Zifencei => IType
  | CSRRW_32Zicsr      => IType  | CSRRS_32Zicsr      => IType
  | CSRRC_32Zicsr      => IType  | CSRRWI_32Zicsr     => IType
  | CSRRSI_32Zicsr     => IType  | CSRRCI_32Zicsr     => IType
  | CSRRW_64Zicsr      => IType  | CSRRS_64Zicsr      => IType
  | CSRRC_64Zicsr      => IType  | CSRRWI_64Zicsr     => IType
  | CSRRSI_64Zicsr     => IType  | CSRRCI_64Zicsr     => IType
  | MUL_32M            => RType  | MULH_32M           => RType
  | MULHSU_32M         => RType  | MULHU_32M          => RType
  | DIV_32M            => RType  | DIVU_32M           => RType
  | REM_32M            => RType  | REMU_32M           => RType
  | MUL_64M            => RType  | MULH_64M           => RType
  | MULHSU_64M         => RType  | MULHU_64M          => RType
  | DIV_64M            => RType  | DIVU_64M           => RType
  | REM_64M            => RType  | REMU_64M           => RType
  | MULW_64M           => RType  | DIVW_64M           => RType
  | DIVUW_64M          => RType  | REMW_64M           => RType
  | REMUW_64M          => RType  | LR_W_00_32A        => RType
  | LR_W_01_32A        => RType  | LR_W_10_32A        => RType
  | LR_W_11_32A        => RType  | SC_W_00_32A        => RType
  | SC_W_01_32A        => RType  | SC_W_10_32A        => RType
  | SC_W_11_32A        => RType  | AMOSWAP_W_00_32A   => RType
  | AMOSWAP_W_01_32A   => RType  | AMOSWAP_W_10_32A   => RType
  | AMOSWAP_W_11_32A   => RType  | AMOADD_W_00_32A    => RType
  | AMOADD_W_01_32A    => RType  | AMOADD_W_10_32A    => RType
  | AMOADD_W_11_32A    => RType  | AMOXOR_W_00_32A    => RType
  | AMOXOR_W_01_32A    => RType  | AMOXOR_W_10_32A    => RType
  | AMOXOR_W_11_32A    => RType  | AMOAND_W_00_32A    => RType
  | AMOAND_W_01_32A    => RType  | AMOAND_W_10_32A    => RType
  | AMOAND_W_11_32A    => RType  | AMOOR_W_00_32A     => RType
  | AMOOR_W_01_32A     => RType  | AMOOR_W_10_32A     => RType
  | AMOOR_W_11_32A     => RType  | AMOMIN_W_00_32A    => RType
  | AMOMIN_W_01_32A    => RType  | AMOMIN_W_10_32A    => RType
  | AMOMIN_W_11_32A    => RType  | AMOMAX_W_00_32A    => RType
  | AMOMAX_W_01_32A    => RType  | AMOMAX_W_10_32A    => RType
  | AMOMAX_W_11_32A    => RType  | AMOMINU_W_00_32A   => RType
  | AMOMINU_W_01_32A   => RType  | AMOMINU_W_10_32A   => RType
  | AMOMINU_W_11_32A   => RType  | AMOMAXU_W_00_32A   => RType
  | AMOMAXU_W_01_32A   => RType  | AMOMAXU_W_10_32A   => RType
  | AMOMAXU_W_11_32A   => RType  | LR_W_00_64A        => RType
  | LR_W_01_64A        => RType  | LR_W_10_64A        => RType
  | LR_W_11_64A        => RType  | SC_W_00_64A        => RType
  | SC_W_01_64A        => RType  | SC_W_10_64A        => RType
  | SC_W_11_64A        => RType  | AMOSWAP_W_00_64A   => RType
  | AMOSWAP_W_01_64A   => RType  | AMOSWAP_W_10_64A   => RType
  | AMOSWAP_W_11_64A   => RType  | AMOADD_W_00_64A    => RType
  | AMOADD_W_01_64A    => RType  | AMOADD_W_10_64A    => RType
  | AMOADD_W_11_64A    => RType  | AMOXOR_W_00_64A    => RType
  | AMOXOR_W_01_64A    => RType  | AMOXOR_W_10_64A    => RType
  | AMOXOR_W_11_64A    => RType  | AMOAND_W_00_64A    => RType
  | AMOAND_W_01_64A    => RType  | AMOAND_W_10_64A    => RType
  | AMOAND_W_11_64A    => RType  | AMOOR_W_00_64A     => RType
  | AMOOR_W_01_64A     => RType  | AMOOR_W_10_64A     => RType
  | AMOOR_W_11_64A     => RType  | AMOMIN_W_00_64A    => RType
  | AMOMIN_W_01_64A    => RType  | AMOMIN_W_10_64A    => RType
  | AMOMIN_W_11_64A    => RType  | AMOMAX_W_00_64A    => RType
  | AMOMAX_W_01_64A    => RType  | AMOMAX_W_10_64A    => RType
  | AMOMAX_W_11_64A    => RType  | AMOMINU_W_00_64A   => RType
  | AMOMINU_W_01_64A   => RType  | AMOMINU_W_10_64A   => RType
  | AMOMINU_W_11_64A   => RType  | AMOMAXU_W_00_64A   => RType
  | AMOMAXU_W_01_64A   => RType  | AMOMAXU_W_10_64A   => RType
  | AMOMAXU_W_11_64A   => RType  | LR_D_00_64A        => RType
  | LR_D_01_64A        => RType  | LR_D_10_64A        => RType
  | LR_D_11_64A        => RType  | SC_D_00_64A        => RType
  | SC_D_01_64A        => RType  | SC_D_10_64A        => RType
  | SC_D_11_64A        => RType  | AMOSWAP_D_00_64A   => RType
  | AMOSWAP_D_01_64A   => RType  | AMOSWAP_D_10_64A   => RType
  | AMOSWAP_D_11_64A   => RType  | AMOADD_D_00_64A    => RType
  | AMOADD_D_01_64A    => RType  | AMOADD_D_10_64A    => RType
  | AMOADD_D_11_64A    => RType  | AMOXOR_D_00_64A    => RType
  | AMOXOR_D_01_64A    => RType  | AMOXOR_D_10_64A    => RType
  | AMOXOR_D_11_64A    => RType  | AMOAND_D_00_64A    => RType
  | AMOAND_D_01_64A    => RType  | AMOAND_D_10_64A    => RType
  | AMOAND_D_11_64A    => RType  | AMOOR_D_00_64A     => RType
  | AMOOR_D_01_64A     => RType  | AMOOR_D_10_64A     => RType
  | AMOOR_D_11_64A     => RType  | AMOMIN_D_00_64A    => RType
  | AMOMIN_D_01_64A    => RType  | AMOMIN_D_10_64A    => RType
  | AMOMIN_D_11_64A    => RType  | AMOMAX_D_00_64A    => RType
  | AMOMAX_D_01_64A    => RType  | AMOMAX_D_10_64A    => RType
  | AMOMAX_D_11_64A    => RType  | AMOMINU_D_00_64A   => RType
  | AMOMINU_D_01_64A   => RType  | AMOMINU_D_10_64A   => RType
  | AMOMINU_D_11_64A   => RType  | AMOMAXU_D_00_64A   => RType
  | AMOMAXU_D_01_64A   => RType  | AMOMAXU_D_10_64A   => RType
  | AMOMAXU_D_11_64A   => RType  | FLW_32F            => IType
  | FSW_32F            => SType  | FMADD_RNE_S_32F    => R4Type
  | FMADD_RTZ_S_32F    => R4Type | FMADD_RDN_S_32F    => R4Type
  | FMADD_RUP_S_32F    => R4Type | FMADD_RMM_S_32F    => R4Type
  | FMADD_DYN_S_32F    => R4Type | FMSUB_RNE_S_32F    => R4Type
  | FMSUB_RTZ_S_32F    => R4Type | FMSUB_RDN_S_32F    => R4Type
  | FMSUB_RUP_S_32F    => R4Type | FMSUB_RMM_S_32F    => R4Type
  | FMSUB_DYN_S_32F    => R4Type | FNMSUB_RNE_S_32F   => R4Type
  | FNMSUB_RTZ_S_32F   => R4Type | FNMSUB_RDN_S_32F   => R4Type
  | FNMSUB_RUP_S_32F   => R4Type | FNMSUB_RMM_S_32F   => R4Type
  | FNMSUB_DYN_S_32F   => R4Type | FNMADD_RNE_S_32F   => R4Type
  | FNMADD_RTZ_S_32F   => R4Type | FNMADD_RDN_S_32F   => R4Type
  | FNMADD_RUP_S_32F   => R4Type | FNMADD_RMM_S_32F   => R4Type
  | FNMADD_DYN_S_32F   => R4Type | FADD_RNE_S_32F     => RType
  | FADD_RTZ_S_32F     => RType  | FADD_RDN_S_32F     => RType
  | FADD_RUP_S_32F     => RType  | FADD_RMM_S_32F     => RType
  | FADD_DYN_S_32F     => RType  | FSUB_RNE_S_32F     => RType
  | FSUB_RTZ_S_32F     => RType  | FSUB_RDN_S_32F     => RType
  | FSUB_RUP_S_32F     => RType  | FSUB_RMM_S_32F     => RType
  | FSUB_DYN_S_32F     => RType  | FMUL_RNE_S_32F     => RType
  | FMUL_RTZ_S_32F     => RType  | FMUL_RDN_S_32F     => RType
  | FMUL_RUP_S_32F     => RType  | FMUL_RMM_S_32F     => RType
  | FMUL_DYN_S_32F     => RType  | FDIV_RNE_S_32F     => RType
  | FDIV_RTZ_S_32F     => RType  | FDIV_RDN_S_32F     => RType
  | FDIV_RUP_S_32F     => RType  | FDIV_RMM_S_32F     => RType
  | FDIV_DYN_S_32F     => RType  | FSQRT_RNE_S_32F    => RType
  | FSQRT_RTZ_S_32F    => RType  | FSQRT_RDN_S_32F    => RType
  | FSQRT_RUP_S_32F    => RType  | FSQRT_RMM_S_32F    => RType
  | FSQRT_DYN_S_32F    => RType  | FSGNJ_S_32F        => RType
  | FSGNJN_S_32F       => RType  | FSGNJX_S_32F       => RType
  | FMIN_S_32F         => RType  | FMAX_S_32F         => RType
  | FCVT_RNE_W_S_32F   => RType  | FCVT_RTZ_W_S_32F   => RType
  | FCVT_RDN_W_S_32F   => RType  | FCVT_RUP_W_S_32F   => RType
  | FCVT_RMM_W_S_32F   => RType  | FCVT_DYN_W_S_32F   => RType
  | FCVT_RNE_WU_S_32F  => RType  | FCVT_RTZ_WU_S_32F  => RType
  | FCVT_RDN_WU_S_32F  => RType  | FCVT_RUP_WU_S_32F  => RType
  | FCVT_RMM_WU_S_32F  => RType  | FCVT_DYN_WU_S_32F  => RType
  | FMV_X_W_32F        => RType  | FEQ_S_32F          => RType
  | FLT_S_32F          => RType  | FLE_S_32F          => RType
  | FCLASS_S_32F       => RType  | FCVT_RNE_S_W_32F   => RType
  | FCVT_RTZ_S_W_32F   => RType  | FCVT_RDN_S_W_32F   => RType
  | FCVT_RUP_S_W_32F   => RType  | FCVT_RMM_S_W_32F   => RType
  | FCVT_DYN_S_W_32F   => RType  | FCVT_RNE_S_WU_32F  => RType
  | FCVT_RTZ_S_WU_32F  => RType  | FCVT_RDN_S_WU_32F  => RType
  | FCVT_RUP_S_WU_32F  => RType  | FCVT_RMM_S_WU_32F  => RType
  | FCVT_DYN_S_WU_32F  => RType  | FMV_W_X_32F        => RType
  | FLW_64F            => IType  | FSW_64F            => SType
  | FMADD_RNE_S_64F    => R4Type | FMADD_RTZ_S_64F    => R4Type
  | FMADD_RDN_S_64F    => R4Type | FMADD_RUP_S_64F    => R4Type
  | FMADD_RMM_S_64F    => R4Type | FMADD_DYN_S_64F    => R4Type
  | FMSUB_RNE_S_64F    => R4Type | FMSUB_RTZ_S_64F    => R4Type
  | FMSUB_RDN_S_64F    => R4Type | FMSUB_RUP_S_64F    => R4Type
  | FMSUB_RMM_S_64F    => R4Type | FMSUB_DYN_S_64F    => R4Type
  | FNMSUB_RNE_S_64F   => R4Type | FNMSUB_RTZ_S_64F   => R4Type
  | FNMSUB_RDN_S_64F   => R4Type | FNMSUB_RUP_S_64F   => R4Type
  | FNMSUB_RMM_S_64F   => R4Type | FNMSUB_DYN_S_64F   => R4Type
  | FNMADD_RNE_S_64F   => R4Type | FNMADD_RTZ_S_64F   => R4Type
  | FNMADD_RDN_S_64F   => R4Type | FNMADD_RUP_S_64F   => R4Type
  | FNMADD_RMM_S_64F   => R4Type | FNMADD_DYN_S_64F   => R4Type
  | FADD_RNE_S_64F     => RType  | FADD_RTZ_S_64F     => RType
  | FADD_RDN_S_64F     => RType  | FADD_RUP_S_64F     => RType
  | FADD_RMM_S_64F     => RType  | FADD_DYN_S_64F     => RType
  | FSUB_RNE_S_64F     => RType  | FSUB_RTZ_S_64F     => RType
  | FSUB_RDN_S_64F     => RType  | FSUB_RUP_S_64F     => RType
  | FSUB_RMM_S_64F     => RType  | FSUB_DYN_S_64F     => RType
  | FMUL_RNE_S_64F     => RType  | FMUL_RTZ_S_64F     => RType
  | FMUL_RDN_S_64F     => RType  | FMUL_RUP_S_64F     => RType
  | FMUL_RMM_S_64F     => RType  | FMUL_DYN_S_64F     => RType
  | FDIV_RNE_S_64F     => RType  | FDIV_RTZ_S_64F     => RType
  | FDIV_RDN_S_64F     => RType  | FDIV_RUP_S_64F     => RType
  | FDIV_RMM_S_64F     => RType  | FDIV_DYN_S_64F     => RType
  | FSQRT_RNE_S_64F    => RType  | FSQRT_RTZ_S_64F    => RType
  | FSQRT_RDN_S_64F    => RType  | FSQRT_RUP_S_64F    => RType
  | FSQRT_RMM_S_64F    => RType  | FSQRT_DYN_S_64F    => RType
  | FSGNJ_S_64F        => RType  | FSGNJN_S_64F       => RType
  | FSGNJX_S_64F       => RType  | FMIN_S_64F         => RType
  | FMAX_S_64F         => RType  | FCVT_RNE_W_S_64F   => RType
  | FCVT_RTZ_W_S_64F   => RType  | FCVT_RDN_W_S_64F   => RType
  | FCVT_RUP_W_S_64F   => RType  | FCVT_RMM_W_S_64F   => RType
  | FCVT_DYN_W_S_64F   => RType  | FCVT_RNE_WU_S_64F  => RType
  | FCVT_RTZ_WU_S_64F  => RType  | FCVT_RDN_WU_S_64F  => RType
  | FCVT_RUP_WU_S_64F  => RType  | FCVT_RMM_WU_S_64F  => RType
  | FCVT_DYN_WU_S_64F  => RType  | FMV_X_W_64F        => RType
  | FEQ_S_64F          => RType  | FLT_S_64F          => RType
  | FLE_S_64F          => RType  | FCLASS_S_64F       => RType
  | FCVT_RNE_S_W_64F   => RType  | FCVT_RTZ_S_W_64F   => RType
  | FCVT_RDN_S_W_64F   => RType  | FCVT_RUP_S_W_64F   => RType
  | FCVT_RMM_S_W_64F   => RType  | FCVT_DYN_S_W_64F   => RType
  | FCVT_RNE_S_WU_64F  => RType  | FCVT_RTZ_S_WU_64F  => RType
  | FCVT_RDN_S_WU_64F  => RType  | FCVT_RUP_S_WU_64F  => RType
  | FCVT_RMM_S_WU_64F  => RType  | FCVT_DYN_S_WU_64F  => RType
  | FMV_W_X_64F        => RType  | FCVT_RNE_L_S_64F   => RType
  | FCVT_RTZ_L_S_64F   => RType  | FCVT_RDN_L_S_64F   => RType
  | FCVT_RUP_L_S_64F   => RType  | FCVT_RMM_L_S_64F   => RType
  | FCVT_DYN_L_S_64F   => RType  | FCVT_RNE_LU_S_64F  => RType
  | FCVT_RTZ_LU_S_64F  => RType  | FCVT_RDN_LU_S_64F  => RType
  | FCVT_RUP_LU_S_64F  => RType  | FCVT_RMM_LU_S_64F  => RType
  | FCVT_DYN_LU_S_64F  => RType  | FCVT_RNE_S_L_64F   => RType
  | FCVT_RTZ_S_L_64F   => RType  | FCVT_RDN_S_L_64F   => RType
  | FCVT_RUP_S_L_64F   => RType  | FCVT_RMM_S_L_64F   => RType
  | FCVT_DYN_S_L_64F   => RType  | FCVT_RNE_S_LU_64F  => RType
  | FCVT_RTZ_S_LU_64F  => RType  | FCVT_RDN_S_LU_64F  => RType
  | FCVT_RUP_S_LU_64F  => RType  | FCVT_RMM_S_LU_64F  => RType
  | FCVT_DYN_S_LU_64F  => RType  | FLD_32D            => IType
  | FSD_32D            => SType  | FMADD_RNE_D_32D    => R4Type
  | FMADD_RTZ_D_32D    => R4Type | FMADD_RDN_D_32D    => R4Type
  | FMADD_RUP_D_32D    => R4Type | FMADD_RMM_D_32D    => R4Type
  | FMADD_DYN_D_32D    => R4Type | FMSUB_RNE_D_32D    => R4Type
  | FMSUB_RTZ_D_32D    => R4Type | FMSUB_RDN_D_32D    => R4Type
  | FMSUB_RUP_D_32D    => R4Type | FMSUB_RMM_D_32D    => R4Type
  | FMSUB_DYN_D_32D    => R4Type | FNMSUB_RNE_D_32D   => R4Type
  | FNMSUB_RTZ_D_32D   => R4Type | FNMSUB_RDN_D_32D   => R4Type
  | FNMSUB_RUP_D_32D   => R4Type | FNMSUB_RMM_D_32D   => R4Type
  | FNMSUB_DYN_D_32D   => R4Type | FNMADD_RNE_D_32D   => R4Type
  | FNMADD_RTZ_D_32D   => R4Type | FNMADD_RDN_D_32D   => R4Type
  | FNMADD_RUP_D_32D   => R4Type | FNMADD_RMM_D_32D   => R4Type
  | FNMADD_DYN_D_32D   => R4Type | FADD_RNE_D_32D     => RType
  | FADD_RTZ_D_32D     => RType  | FADD_RDN_D_32D     => RType
  | FADD_RUP_D_32D     => RType  | FADD_RMM_D_32D     => RType
  | FADD_DYN_D_32D     => RType  | FSUB_RNE_D_32D     => RType
  | FSUB_RTZ_D_32D     => RType  | FSUB_RDN_D_32D     => RType
  | FSUB_RUP_D_32D     => RType  | FSUB_RMM_D_32D     => RType
  | FSUB_DYN_D_32D     => RType  | FMUL_RNE_D_32D     => RType
  | FMUL_RTZ_D_32D     => RType  | FMUL_RDN_D_32D     => RType
  | FMUL_RUP_D_32D     => RType  | FMUL_RMM_D_32D     => RType
  | FMUL_DYN_D_32D     => RType  | FDIV_RNE_D_32D     => RType
  | FDIV_RTZ_D_32D     => RType  | FDIV_RDN_D_32D     => RType
  | FDIV_RUP_D_32D     => RType  | FDIV_RMM_D_32D     => RType
  | FDIV_DYN_D_32D     => RType  | FSQRT_RNE_D_32D    => RType
  | FSQRT_RTZ_D_32D    => RType  | FSQRT_RDN_D_32D    => RType
  | FSQRT_RUP_D_32D    => RType  | FSQRT_RMM_D_32D    => RType
  | FSQRT_DYN_D_32D    => RType  | FSGNJ_D_32D        => RType
  | FSGNJN_D_32D       => RType  | FSGNJX_D_32D       => RType
  | FMIN_D_32D         => RType  | FMAX_D_32D         => RType
  | FCVT_RNE_S_D_32D   => RType  | FCVT_RTZ_S_D_32D   => RType
  | FCVT_RDN_S_D_32D   => RType  | FCVT_RUP_S_D_32D   => RType
  | FCVT_RMM_S_D_32D   => RType  | FCVT_DYN_S_D_32D   => RType
  | FCVT_RNE_D_S_32D   => RType  | FCVT_RTZ_D_S_32D   => RType
  | FCVT_RDN_D_S_32D   => RType  | FCVT_RUP_D_S_32D   => RType
  | FCVT_RMM_D_S_32D   => RType  | FCVT_DYN_D_S_32D   => RType
  | FEQ_D_32D          => RType  | FLT_D_32D          => RType
  | FLE_D_32D          => RType  | FCLASS_D_32D       => RType
  | FCVT_RNE_W_D_32D   => RType  | FCVT_RTZ_W_D_32D   => RType
  | FCVT_RDN_W_D_32D   => RType  | FCVT_RUP_W_D_32D   => RType
  | FCVT_RMM_W_D_32D   => RType  | FCVT_DYN_W_D_32D   => RType
  | FCVT_RNE_WU_D_32D  => RType  | FCVT_RTZ_WU_D_32D  => RType
  | FCVT_RDN_WU_D_32D  => RType  | FCVT_RUP_WU_D_32D  => RType
  | FCVT_RMM_WU_D_32D  => RType  | FCVT_DYN_WU_D_32D  => RType
  | FCVT_RNE_D_W_32D   => RType  | FCVT_RTZ_D_W_32D   => RType
  | FCVT_RDN_D_W_32D   => RType  | FCVT_RUP_D_W_32D   => RType
  | FCVT_RMM_D_W_32D   => RType  | FCVT_DYN_D_W_32D   => RType
  | FCVT_RNE_D_WU_32D  => RType  | FCVT_RTZ_D_WU_32D  => RType
  | FCVT_RDN_D_WU_32D  => RType  | FCVT_RUP_D_WU_32D  => RType
  | FCVT_RMM_D_WU_32D  => RType  | FCVT_DYN_D_WU_32D  => RType
  | FLD_64D            => IType  | FSD_64D            => SType
  | FMADD_RNE_D_64D    => R4Type | FMADD_RTZ_D_64D    => R4Type
  | FMADD_RDN_D_64D    => R4Type | FMADD_RUP_D_64D    => R4Type
  | FMADD_RMM_D_64D    => R4Type | FMADD_DYN_D_64D    => R4Type
  | FMSUB_RNE_D_64D    => R4Type | FMSUB_RTZ_D_64D    => R4Type
  | FMSUB_RDN_D_64D    => R4Type | FMSUB_RUP_D_64D    => R4Type
  | FMSUB_RMM_D_64D    => R4Type | FMSUB_DYN_D_64D    => R4Type
  | FNMSUB_RNE_D_64D   => R4Type | FNMSUB_RTZ_D_64D   => R4Type
  | FNMSUB_RDN_D_64D   => R4Type | FNMSUB_RUP_D_64D   => R4Type
  | FNMSUB_RMM_D_64D   => R4Type | FNMSUB_DYN_D_64D   => R4Type
  | FNMADD_RNE_D_64D   => R4Type | FNMADD_RTZ_D_64D   => R4Type
  | FNMADD_RDN_D_64D   => R4Type | FNMADD_RUP_D_64D   => R4Type
  | FNMADD_RMM_D_64D   => R4Type | FNMADD_DYN_D_64D   => R4Type
  | FADD_RNE_D_64D     => RType  | FADD_RTZ_D_64D     => RType
  | FADD_RDN_D_64D     => RType  | FADD_RUP_D_64D     => RType
  | FADD_RMM_D_64D     => RType  | FADD_DYN_D_64D     => RType
  | FSUB_RNE_D_64D     => RType  | FSUB_RTZ_D_64D     => RType
  | FSUB_RDN_D_64D     => RType  | FSUB_RUP_D_64D     => RType
  | FSUB_RMM_D_64D     => RType  | FSUB_DYN_D_64D     => RType
  | FMUL_RNE_D_64D     => RType  | FMUL_RTZ_D_64D     => RType
  | FMUL_RDN_D_64D     => RType  | FMUL_RUP_D_64D     => RType
  | FMUL_RMM_D_64D     => RType  | FMUL_DYN_D_64D     => RType
  | FDIV_RNE_D_64D     => RType  | FDIV_RTZ_D_64D     => RType
  | FDIV_RDN_D_64D     => RType  | FDIV_RUP_D_64D     => RType
  | FDIV_RMM_D_64D     => RType  | FDIV_DYN_D_64D     => RType
  | FSQRT_RNE_D_64D    => RType  | FSQRT_RTZ_D_64D    => RType
  | FSQRT_RDN_D_64D    => RType  | FSQRT_RUP_D_64D    => RType
  | FSQRT_RMM_D_64D    => RType  | FSQRT_DYN_D_64D    => RType
  | FSGNJ_D_64D        => RType  | FSGNJN_D_64D       => RType
  | FSGNJX_D_64D       => RType  | FMIN_D_64D         => RType
  | FMAX_D_64D         => RType  | FCVT_RNE_S_D_64D   => RType
  | FCVT_RTZ_S_D_64D   => RType  | FCVT_RDN_S_D_64D   => RType
  | FCVT_RUP_S_D_64D   => RType  | FCVT_RMM_S_D_64D   => RType
  | FCVT_DYN_S_D_64D   => RType  | FCVT_RNE_D_S_64D   => RType
  | FCVT_RTZ_D_S_64D   => RType  | FCVT_RDN_D_S_64D   => RType
  | FCVT_RUP_D_S_64D   => RType  | FCVT_RMM_D_S_64D   => RType
  | FCVT_DYN_D_S_64D   => RType  | FEQ_D_64D          => RType
  | FLT_D_64D          => RType  | FLE_D_64D          => RType
  | FCLASS_D_64D       => RType  | FCVT_RNE_W_D_64D   => RType
  | FCVT_RTZ_W_D_64D   => RType  | FCVT_RDN_W_D_64D   => RType
  | FCVT_RUP_W_D_64D   => RType  | FCVT_RMM_W_D_64D   => RType
  | FCVT_DYN_W_D_64D   => RType  | FCVT_RNE_WU_D_64D  => RType
  | FCVT_RTZ_WU_D_64D  => RType  | FCVT_RDN_WU_D_64D  => RType
  | FCVT_RUP_WU_D_64D  => RType  | FCVT_RMM_WU_D_64D  => RType
  | FCVT_DYN_WU_D_64D  => RType  | FCVT_RNE_D_W_64D   => RType
  | FCVT_RTZ_D_W_64D   => RType  | FCVT_RDN_D_W_64D   => RType
  | FCVT_RUP_D_W_64D   => RType  | FCVT_RMM_D_W_64D   => RType
  | FCVT_DYN_D_W_64D   => RType  | FCVT_RNE_D_WU_64D  => RType
  | FCVT_RTZ_D_WU_64D  => RType  | FCVT_RDN_D_WU_64D  => RType
  | FCVT_RUP_D_WU_64D  => RType  | FCVT_RMM_D_WU_64D  => RType
  | FCVT_DYN_D_WU_64D  => RType  | FCVT_RNE_L_D_64D   => RType
  | FCVT_RTZ_L_D_64D   => RType  | FCVT_RDN_L_D_64D   => RType
  | FCVT_RUP_L_D_64D   => RType  | FCVT_RMM_L_D_64D   => RType
  | FCVT_DYN_L_D_64D   => RType  | FCVT_RNE_LU_D_64D  => RType
  | FCVT_RTZ_LU_D_64D  => RType  | FCVT_RDN_LU_D_64D  => RType
  | FCVT_RUP_LU_D_64D  => RType  | FCVT_RMM_LU_D_64D  => RType
  | FCVT_DYN_LU_D_64D  => RType  | FMV_X_D_64D        => RType
  | FCVT_RNE_D_L_64D   => RType  | FCVT_RTZ_D_L_64D   => RType
  | FCVT_RDN_D_L_64D   => RType  | FCVT_RUP_D_L_64D   => RType
  | FCVT_RMM_D_L_64D   => RType  | FCVT_DYN_D_L_64D   => RType
  | FCVT_RNE_D_LU_64D  => RType  | FCVT_RTZ_D_LU_64D  => RType
  | FCVT_RDN_D_LU_64D  => RType  | FCVT_RUP_D_LU_64D  => RType
  | FCVT_RMM_D_LU_64D  => RType  | FCVT_DYN_D_LU_64D  => RType
  | FMV_D_X_64D        => RType  | FLQ_32Q            => IType
  | FSQ_32Q            => SType  | FMADD_RNE_Q_32Q    => R4Type
  | FMADD_RTZ_Q_32Q    => R4Type | FMADD_RDN_Q_32Q    => R4Type
  | FMADD_RUP_Q_32Q    => R4Type | FMADD_RMM_Q_32Q    => R4Type
  | FMADD_DYN_Q_32Q    => R4Type | FMSUB_RNE_Q_32Q    => R4Type
  | FMSUB_RTZ_Q_32Q    => R4Type | FMSUB_RDN_Q_32Q    => R4Type
  | FMSUB_RUP_Q_32Q    => R4Type | FMSUB_RMM_Q_32Q    => R4Type
  | FMSUB_DYN_Q_32Q    => R4Type | FNMSUB_RNE_Q_32Q   => R4Type
  | FNMSUB_RTZ_Q_32Q   => R4Type | FNMSUB_RDN_Q_32Q   => R4Type
  | FNMSUB_RUP_Q_32Q   => R4Type | FNMSUB_RMM_Q_32Q   => R4Type
  | FNMSUB_DYN_Q_32Q   => R4Type | FNMADD_RNE_Q_32Q   => R4Type
  | FNMADD_RTZ_Q_32Q   => R4Type | FNMADD_RDN_Q_32Q   => R4Type
  | FNMADD_RUP_Q_32Q   => R4Type | FNMADD_RMM_Q_32Q   => R4Type
  | FNMADD_DYN_Q_32Q   => R4Type | FADD_RNE_Q_32Q     => RType
  | FADD_RTZ_Q_32Q     => RType  | FADD_RDN_Q_32Q     => RType
  | FADD_RUP_Q_32Q     => RType  | FADD_RMM_Q_32Q     => RType
  | FADD_DYN_Q_32Q     => RType  | FSUB_RNE_Q_32Q     => RType
  | FSUB_RTZ_Q_32Q     => RType  | FSUB_RDN_Q_32Q     => RType
  | FSUB_RUP_Q_32Q     => RType  | FSUB_RMM_Q_32Q     => RType
  | FSUB_DYN_Q_32Q     => RType  | FMUL_RNE_Q_32Q     => RType
  | FMUL_RTZ_Q_32Q     => RType  | FMUL_RDN_Q_32Q     => RType
  | FMUL_RUP_Q_32Q     => RType  | FMUL_RMM_Q_32Q     => RType
  | FMUL_DYN_Q_32Q     => RType  | FDIV_RNE_Q_32Q     => RType
  | FDIV_RTZ_Q_32Q     => RType  | FDIV_RDN_Q_32Q     => RType
  | FDIV_RUP_Q_32Q     => RType  | FDIV_RMM_Q_32Q     => RType
  | FDIV_DYN_Q_32Q     => RType  | FSQRT_RNE_Q_32Q    => RType
  | FSQRT_RTZ_Q_32Q    => RType  | FSQRT_RDN_Q_32Q    => RType
  | FSQRT_RUP_Q_32Q    => RType  | FSQRT_RMM_Q_32Q    => RType
  | FSQRT_DYN_Q_32Q    => RType  | FSGNJ_Q_32Q        => RType
  | FSGNJN_Q_32Q       => RType  | FSGNJX_Q_32Q       => RType
  | FMIN_Q_32Q         => RType  | FMAX_Q_32Q         => RType
  | FCVT_RNE_S_Q_32Q   => RType  | FCVT_RTZ_S_Q_32Q   => RType
  | FCVT_RDN_S_Q_32Q   => RType  | FCVT_RUP_S_Q_32Q   => RType
  | FCVT_RMM_S_Q_32Q   => RType  | FCVT_DYN_S_Q_32Q   => RType
  | FCVT_RNE_Q_S_32Q   => RType  | FCVT_RTZ_Q_S_32Q   => RType
  | FCVT_RDN_Q_S_32Q   => RType  | FCVT_RUP_Q_S_32Q   => RType
  | FCVT_RMM_Q_S_32Q   => RType  | FCVT_DYN_Q_S_32Q   => RType
  | FCVT_RNE_D_Q_32Q   => RType  | FCVT_RTZ_D_Q_32Q   => RType
  | FCVT_RDN_D_Q_32Q   => RType  | FCVT_RUP_D_Q_32Q   => RType
  | FCVT_RMM_D_Q_32Q   => RType  | FCVT_DYN_D_Q_32Q   => RType
  | FCVT_RNE_Q_D_32Q   => RType  | FCVT_RTZ_Q_D_32Q   => RType
  | FCVT_RDN_Q_D_32Q   => RType  | FCVT_RUP_Q_D_32Q   => RType
  | FCVT_RMM_Q_D_32Q   => RType  | FCVT_DYN_Q_D_32Q   => RType
  | FEQ_Q_32Q          => RType  | FLT_Q_32Q          => RType
  | FLE_Q_32Q          => RType  | FCLASS_Q_32Q       => RType
  | FCVT_RNE_W_Q_32Q   => RType  | FCVT_RTZ_W_Q_32Q   => RType
  | FCVT_RDN_W_Q_32Q   => RType  | FCVT_RUP_W_Q_32Q   => RType
  | FCVT_RMM_W_Q_32Q   => RType  | FCVT_DYN_W_Q_32Q   => RType
  | FCVT_RNE_WU_Q_32Q  => RType  | FCVT_RTZ_WU_Q_32Q  => RType
  | FCVT_RDN_WU_Q_32Q  => RType  | FCVT_RUP_WU_Q_32Q  => RType
  | FCVT_RMM_WU_Q_32Q  => RType  | FCVT_DYN_WU_Q_32Q  => RType
  | FCVT_RNE_Q_W_32Q   => RType  | FCVT_RTZ_Q_W_32Q   => RType
  | FCVT_RDN_Q_W_32Q   => RType  | FCVT_RUP_Q_W_32Q   => RType
  | FCVT_RMM_Q_W_32Q   => RType  | FCVT_DYN_Q_W_32Q   => RType
  | FCVT_RNE_Q_WU_32Q  => RType  | FCVT_RTZ_Q_WU_32Q  => RType
  | FCVT_RDN_Q_WU_32Q  => RType  | FCVT_RUP_Q_WU_32Q  => RType
  | FCVT_RMM_Q_WU_32Q  => RType  | FCVT_DYN_Q_WU_32Q  => RType
  | FLQ_64Q            => IType  | FSQ_64Q            => SType
  | FMADD_RNE_Q_64Q    => R4Type | FMADD_RTZ_Q_64Q    => R4Type
  | FMADD_RDN_Q_64Q    => R4Type | FMADD_RUP_Q_64Q    => R4Type
  | FMADD_RMM_Q_64Q    => R4Type | FMADD_DYN_Q_64Q    => R4Type
  | FMSUB_RNE_Q_64Q    => R4Type | FMSUB_RTZ_Q_64Q    => R4Type
  | FMSUB_RDN_Q_64Q    => R4Type | FMSUB_RUP_Q_64Q    => R4Type
  | FMSUB_RMM_Q_64Q    => R4Type | FMSUB_DYN_Q_64Q    => R4Type
  | FNMSUB_RNE_Q_64Q   => R4Type | FNMSUB_RTZ_Q_64Q   => R4Type
  | FNMSUB_RDN_Q_64Q   => R4Type | FNMSUB_RUP_Q_64Q   => R4Type
  | FNMSUB_RMM_Q_64Q   => R4Type | FNMSUB_DYN_Q_64Q   => R4Type
  | FNMADD_RNE_Q_64Q   => R4Type | FNMADD_RTZ_Q_64Q   => R4Type
  | FNMADD_RDN_Q_64Q   => R4Type | FNMADD_RUP_Q_64Q   => R4Type
  | FNMADD_RMM_Q_64Q   => R4Type | FNMADD_DYN_Q_64Q   => R4Type
  | FADD_RNE_Q_64Q     => RType  | FADD_RTZ_Q_64Q     => RType
  | FADD_RDN_Q_64Q     => RType  | FADD_RUP_Q_64Q     => RType
  | FADD_RMM_Q_64Q     => RType  | FADD_DYN_Q_64Q     => RType
  | FSUB_RNE_Q_64Q     => RType  | FSUB_RTZ_Q_64Q     => RType
  | FSUB_RDN_Q_64Q     => RType  | FSUB_RUP_Q_64Q     => RType
  | FSUB_RMM_Q_64Q     => RType  | FSUB_DYN_Q_64Q     => RType
  | FMUL_RNE_Q_64Q     => RType  | FMUL_RTZ_Q_64Q     => RType
  | FMUL_RDN_Q_64Q     => RType  | FMUL_RUP_Q_64Q     => RType
  | FMUL_RMM_Q_64Q     => RType  | FMUL_DYN_Q_64Q     => RType
  | FDIV_RNE_Q_64Q     => RType  | FDIV_RTZ_Q_64Q     => RType
  | FDIV_RDN_Q_64Q     => RType  | FDIV_RUP_Q_64Q     => RType
  | FDIV_RMM_Q_64Q     => RType  | FDIV_DYN_Q_64Q     => RType
  | FSQRT_RNE_Q_64Q    => RType  | FSQRT_RTZ_Q_64Q    => RType
  | FSQRT_RDN_Q_64Q    => RType  | FSQRT_RUP_Q_64Q    => RType
  | FSQRT_RMM_Q_64Q    => RType  | FSQRT_DYN_Q_64Q    => RType
  | FSGNJ_Q_64Q        => RType  | FSGNJN_Q_64Q       => RType
  | FSGNJX_Q_64Q       => RType  | FMIN_Q_64Q         => RType
  | FMAX_Q_64Q         => RType  | FCVT_RNE_S_Q_64Q   => RType
  | FCVT_RTZ_S_Q_64Q   => RType  | FCVT_RDN_S_Q_64Q   => RType
  | FCVT_RUP_S_Q_64Q   => RType  | FCVT_RMM_S_Q_64Q   => RType
  | FCVT_DYN_S_Q_64Q   => RType  | FCVT_RNE_Q_S_64Q   => RType
  | FCVT_RTZ_Q_S_64Q   => RType  | FCVT_RDN_Q_S_64Q   => RType
  | FCVT_RUP_Q_S_64Q   => RType  | FCVT_RMM_Q_S_64Q   => RType
  | FCVT_DYN_Q_S_64Q   => RType  | FCVT_RNE_D_Q_64Q   => RType
  | FCVT_RTZ_D_Q_64Q   => RType  | FCVT_RDN_D_Q_64Q   => RType
  | FCVT_RUP_D_Q_64Q   => RType  | FCVT_RMM_D_Q_64Q   => RType
  | FCVT_DYN_D_Q_64Q   => RType  | FCVT_RNE_Q_D_64Q   => RType
  | FCVT_RTZ_Q_D_64Q   => RType  | FCVT_RDN_Q_D_64Q   => RType
  | FCVT_RUP_Q_D_64Q   => RType  | FCVT_RMM_Q_D_64Q   => RType
  | FCVT_DYN_Q_D_64Q   => RType  | FEQ_Q_64Q          => RType
  | FLT_Q_64Q          => RType  | FLE_Q_64Q          => RType
  | FCLASS_Q_64Q       => RType  | FCVT_RNE_W_Q_64Q   => RType
  | FCVT_RTZ_W_Q_64Q   => RType  | FCVT_RDN_W_Q_64Q   => RType
  | FCVT_RUP_W_Q_64Q   => RType  | FCVT_RMM_W_Q_64Q   => RType
  | FCVT_DYN_W_Q_64Q   => RType  | FCVT_RNE_WU_Q_64Q  => RType
  | FCVT_RTZ_WU_Q_64Q  => RType  | FCVT_RDN_WU_Q_64Q  => RType
  | FCVT_RUP_WU_Q_64Q  => RType  | FCVT_RMM_WU_Q_64Q  => RType
  | FCVT_DYN_WU_Q_64Q  => RType  | FCVT_RNE_Q_W_64Q   => RType
  | FCVT_RTZ_Q_W_64Q   => RType  | FCVT_RDN_Q_W_64Q   => RType
  | FCVT_RUP_Q_W_64Q   => RType  | FCVT_RMM_Q_W_64Q   => RType
  | FCVT_DYN_Q_W_64Q   => RType  | FCVT_RNE_Q_WU_64Q  => RType
  | FCVT_RTZ_Q_WU_64Q  => RType  | FCVT_RDN_Q_WU_64Q  => RType
  | FCVT_RUP_Q_WU_64Q  => RType  | FCVT_RMM_Q_WU_64Q  => RType
  | FCVT_DYN_Q_WU_64Q  => RType  | FCVT_RNE_L_Q_64Q   => RType
  | FCVT_RTZ_L_Q_64Q   => RType  | FCVT_RDN_L_Q_64Q   => RType
  | FCVT_RUP_L_Q_64Q   => RType  | FCVT_RMM_L_Q_64Q   => RType
  | FCVT_DYN_L_Q_64Q   => RType  | FCVT_RNE_LU_Q_64Q  => RType
  | FCVT_RTZ_LU_Q_64Q  => RType  | FCVT_RDN_LU_Q_64Q  => RType
  | FCVT_RUP_LU_Q_64Q  => RType  | FCVT_RMM_LU_Q_64Q  => RType
  | FCVT_DYN_LU_Q_64Q  => RType  | FCVT_RNE_Q_L_64Q   => RType
  | FCVT_RTZ_Q_L_64Q   => RType  | FCVT_RDN_Q_L_64Q   => RType
  | FCVT_RUP_Q_L_64Q   => RType  | FCVT_RMM_Q_L_64Q   => RType
  | FCVT_DYN_Q_L_64Q   => RType  | FCVT_RNE_Q_LU_64Q  => RType
  | FCVT_RTZ_Q_LU_64Q  => RType  | FCVT_RDN_Q_LU_64Q  => RType
  | FCVT_RUP_Q_LU_64Q  => RType  | FCVT_RMM_Q_LU_64Q  => RType
  | FCVT_DYN_Q_LU_64Q  => RType
  end.
