Require Import Koika.Frontend.
Require Import rv.Instructions rv.IFields rv.ITypes.

Inductive fct3_type :=
| fct3_ADD    | fct3_SUB    | fct3_SLL     | fct3_SLT    | fct3_SLTU
| fct3_XOR    | fct3_SRL    | fct3_SRA     | fct3_OR     | fct3_AND
| fct3_LB     | fct3_LH     | fct3_LW      | fct3_LBU    | fct3_LHU
| fct3_SLTI   | fct3_SLTIU  | fct3_ADDI    | fct3_XORI   | fct3_ORI
| fct3_ANDI   | fct3_SLLI   | fct3_SRLI    | fct3_SRAI   | fct3_FENCE
| fct3_SB     | fct3_SH     | fct3_SW      | fct3_BEQ    | fct3_BNE
| fct3_BLT    | fct3_BGE    | fct3_BLTU    | fct3_BGEU   | fct3_PRIV
| fct3_ADDW   | fct3_SUBW   | fct3_SLLW    | fct3_SRLW   | fct3_SRAW
| fct3_LWU    | fct3_LD     | fct3_ADDIW   | fct3_SLLIW  | fct3_SRLIW
| fct3_SRAIW  | fct3_SD     | fct3_FENCE_I | fct3_CSRRW  | fct3_CSRRS
| fct3_CSRRC  | fct3_CSRRWI | fct3_CSRRSI  | fct3_CSRRCI | fct3_MUL
| fct3_MULH   | fct3_MULHSU | fct3_MULHU   | fct3_DIV    | fct3_DIVU
| fct3_REM    | fct3_REMU   | fct3_MULW    | fct3_DIVW   | fct3_DIVUW
| fct3_REMW   | fct3_REMUW  | fct3_AMOW    | fct3_AMOD   | fct3_FSGNJ
| fct3_FSGNJN | fct3_FSGNJX | fct3_FMIN    | fct3_FMAX   | fct3_FMV
| fct3_FEQ    | fct3_FLT    | fct3_FLE     | fct3_FCLASS | fct3_FLW
| fct3_FSW    | fct3_JALR   | fct3_AW      | fct3_AD     | fct3_RNE
| fct3_RTZ    | fct3_RDN    | fct3_RUP     | fct3_RMM    | fct3_DYN
| fct3_LSF    | fct3_LSD    | fct3_LSQ.

Definition fct3_bin (f : fct3_type) :=
  match f with
  | fct3_ADD    => Ob~0~0~0 | fct3_SUB    => Ob~0~0~0 | fct3_SLL     => Ob~0~0~1
  | fct3_SLT    => Ob~0~1~0 | fct3_SLTU   => Ob~0~1~1 | fct3_XOR     => Ob~1~0~0
  | fct3_SRL    => Ob~1~0~1 | fct3_SRA    => Ob~1~0~1 | fct3_OR      => Ob~1~1~0
  | fct3_AND    => Ob~1~1~1 | fct3_LB     => Ob~0~0~0 | fct3_LH      => Ob~0~0~1
  | fct3_LW     => Ob~0~1~0 | fct3_LBU    => Ob~1~0~0 | fct3_LHU     => Ob~1~0~1
  | fct3_SLTI   => Ob~0~1~0 | fct3_SLTIU  => Ob~0~1~1 | fct3_ADDI    => Ob~0~0~0
  | fct3_XORI   => Ob~1~0~0 | fct3_ORI    => Ob~1~1~0 | fct3_ANDI    => Ob~1~1~1
  | fct3_SLLI   => Ob~0~0~1 | fct3_SRLI   => Ob~1~0~1 | fct3_SRAI    => Ob~1~0~1
  | fct3_FENCE  => Ob~0~0~0 | fct3_SB     => Ob~0~0~0 | fct3_SH      => Ob~0~0~1
  | fct3_SW     => Ob~0~1~0 | fct3_BEQ    => Ob~0~0~0 | fct3_BNE     => Ob~0~0~1
  | fct3_BLT    => Ob~1~0~0 | fct3_BGE    => Ob~1~0~1 | fct3_BLTU    => Ob~1~1~0
  | fct3_BGEU   => Ob~1~1~1 | fct3_PRIV   => Ob~0~0~0 | fct3_ADDW    => Ob~0~0~0
  | fct3_SUBW   => Ob~0~0~0 | fct3_SLLW   => Ob~0~0~1 | fct3_SRLW    => Ob~1~0~1
  | fct3_SRAW   => Ob~1~0~1 | fct3_LWU    => Ob~1~1~0 | fct3_LD      => Ob~0~1~1
  | fct3_ADDIW  => Ob~0~0~0 | fct3_SLLIW  => Ob~0~0~1 | fct3_SRLIW   => Ob~1~0~1
  | fct3_SRAIW  => Ob~1~0~1 | fct3_SD     => Ob~0~1~1 | fct3_FENCE_I => Ob~0~0~1
  | fct3_CSRRW  => Ob~0~0~1 | fct3_CSRRS  => Ob~0~1~0 | fct3_CSRRC   => Ob~0~1~1
  | fct3_CSRRWI => Ob~1~0~1 | fct3_CSRRSI => Ob~1~1~0 | fct3_CSRRCI  => Ob~1~1~1
  | fct3_MUL    => Ob~0~0~0 | fct3_MULH   => Ob~0~0~1 | fct3_MULHSU  => Ob~0~1~0
  | fct3_MULHU  => Ob~0~1~1 | fct3_DIV    => Ob~1~0~0 | fct3_DIVU    => Ob~1~0~1
  | fct3_REM    => Ob~1~1~0 | fct3_REMU   => Ob~1~1~1 | fct3_MULW    => Ob~0~0~0
  | fct3_DIVW   => Ob~1~0~0 | fct3_DIVUW  => Ob~1~0~1 | fct3_REMW    => Ob~1~1~0
  | fct3_REMUW  => Ob~1~1~1 | fct3_AMOW   => Ob~0~1~0 | fct3_AMOD    => Ob~0~1~1
  | fct3_FSGNJ  => Ob~0~0~0 | fct3_FSGNJN => Ob~0~0~1 | fct3_FSGNJX  => Ob~0~1~0
  | fct3_FMIN   => Ob~0~0~0 | fct3_FMAX   => Ob~0~0~1 | fct3_FMV     => Ob~0~0~0
  | fct3_FEQ    => Ob~0~1~0 | fct3_FLT    => Ob~0~0~1 | fct3_FLE     => Ob~0~0~0
  | fct3_FCLASS => Ob~0~0~1 | fct3_FLW    => Ob~0~1~0 | fct3_FSW     => Ob~0~1~0
  | fct3_JALR   => Ob~0~0~0 | fct3_AW     => Ob~0~1~0 | fct3_AD      => Ob~0~1~1
  | fct3_RNE    => Ob~0~0~0 | fct3_RTZ    => Ob~0~0~1 | fct3_RDN     => Ob~0~1~0
  | fct3_RUP    => Ob~0~1~1 | fct3_RMM    => Ob~1~0~0 | fct3_DYN     => Ob~1~1~1
  | fct3_LSF    => Ob~0~1~0 | fct3_LSD    => Ob~0~1~1 | fct3_LSQ     => Ob~1~0~0
  end.

Definition instruction_fct3 :
  forall (i : instruction), has_fct3 (get_instruction_i_type i) = true
  -> fct3_type.
Proof.
refine (fun i =>
  match i with
  | JALR_32I           => fun _ => fct3_JALR
  | BEQ_32I            => fun _ => fct3_BEQ
  | BNE_32I            => fun _ => fct3_BNE
  | BLT_32I            => fun _ => fct3_BLT
  | BGE_32I            => fun _ => fct3_BGE
  | BLTU_32I           => fun _ => fct3_BLTU
  | BGEU_32I           => fun _ => fct3_BGEU
  | LB_32I             => fun _ => fct3_LB
  | LH_32I             => fun _ => fct3_LH
  | LW_32I             => fun _ => fct3_LW
  | LBU_32I            => fun _ => fct3_LBU
  | LHU_32I            => fun _ => fct3_LHU
  | SB_32I             => fun _ => fct3_SB
  | SH_32I             => fun _ => fct3_SH
  | SW_32I             => fun _ => fct3_SW
  | ADDI_32I           => fun _ => fct3_ADDI
  | SLTI_32I           => fun _ => fct3_SLTI
  | SLTIU_32I          => fun _ => fct3_SLTIU
  | XORI_32I           => fun _ => fct3_XORI
  | ORI_32I            => fun _ => fct3_ORI
  | ANDI_32I           => fun _ => fct3_ANDI
  | SLLI_32I           => fun _ => fct3_SLLI
  | SRLI_32I           => fun _ => fct3_SRLI
  | SRAI_32I           => fun _ => fct3_SRAI
  | ADD_32I            => fun _ => fct3_ADD
  | SUB_32I            => fun _ => fct3_SUB
  | SLL_32I            => fun _ => fct3_SLL
  | SLT_32I            => fun _ => fct3_SLT
  | SLTU_32I           => fun _ => fct3_SLTU
  | XOR_32I            => fun _ => fct3_XOR
  | SRL_32I            => fun _ => fct3_SRL
  | SRA_32I            => fun _ => fct3_SRA
  | OR_32I             => fun _ => fct3_OR
  | AND_32I            => fun _ => fct3_AND
  | FENCE_32I          => fun _ => fct3_FENCE
  | ECALL_32I          => fun _ => fct3_PRIV
  | EBREAK_32I         => fun _ => fct3_PRIV
  | JALR_64I           => fun _ => fct3_JALR
  | BEQ_64I            => fun _ => fct3_BEQ
  | BNE_64I            => fun _ => fct3_BNE
  | BLT_64I            => fun _ => fct3_BLT
  | BGE_64I            => fun _ => fct3_BGE
  | BLTU_64I           => fun _ => fct3_BLTU
  | BGEU_64I           => fun _ => fct3_BGEU
  | LB_64I             => fun _ => fct3_LB
  | LH_64I             => fun _ => fct3_LH
  | LW_64I             => fun _ => fct3_LW
  | LBU_64I            => fun _ => fct3_LBU
  | LHU_64I            => fun _ => fct3_LHU
  | SB_64I             => fun _ => fct3_SB
  | SH_64I             => fun _ => fct3_SH
  | SW_64I             => fun _ => fct3_SW
  | ADDI_64I           => fun _ => fct3_ADDI
  | SLTI_64I           => fun _ => fct3_SLTI
  | SLTIU_64I          => fun _ => fct3_SLTIU
  | XORI_64I           => fun _ => fct3_XORI
  | ORI_64I            => fun _ => fct3_ORI
  | ANDI_64I           => fun _ => fct3_ANDI
  | SLLI_64I           => fun _ => fct3_SLLI
  | SRLI_64I           => fun _ => fct3_SRLI
  | SRAI_64I           => fun _ => fct3_SRAI
  | ADD_64I            => fun _ => fct3_ADD
  | SUB_64I            => fun _ => fct3_SUB
  | SLL_64I            => fun _ => fct3_SLL
  | SLT_64I            => fun _ => fct3_SLT
  | SLTU_64I           => fun _ => fct3_SLTU
  | XOR_64I            => fun _ => fct3_XOR
  | SRL_64I            => fun _ => fct3_SRL
  | SRA_64I            => fun _ => fct3_SRA
  | OR_64I             => fun _ => fct3_OR
  | AND_64I            => fun _ => fct3_AND
  | FENCE_64I          => fun _ => fct3_FENCE
  | ECALL_64I          => fun _ => fct3_PRIV
  | EBREAK_64I         => fun _ => fct3_PRIV
  | LWU_64I            => fun _ => fct3_LWU
  | LD_64I             => fun _ => fct3_LD
  | SD_64I             => fun _ => fct3_SD
  | ADDIW_64I          => fun _ => fct3_ADDIW
  | SLLIW_64I          => fun _ => fct3_SLLIW
  | SRLIW_64I          => fun _ => fct3_SRLIW
  | SRAIW_64I          => fun _ => fct3_SRAIW
  | ADDW_64I           => fun _ => fct3_ADDW
  | SUBW_64I           => fun _ => fct3_SUBW
  | SLLW_64I           => fun _ => fct3_SLLW
  | SRLW_64I           => fun _ => fct3_SRLW
  | SRAW_64I           => fun _ => fct3_SRAW
  | FENCE_I_32Zifencei => fun _ => fct3_FENCE_I
  | FENCE_I_64Zifencei => fun _ => fct3_FENCE_I
  | CSRRW_32Zicsr      => fun _ => fct3_CSRRW
  | CSRRS_32Zicsr      => fun _ => fct3_CSRRS
  | CSRRC_32Zicsr      => fun _ => fct3_CSRRC
  | CSRRWI_32Zicsr     => fun _ => fct3_CSRRWI
  | CSRRSI_32Zicsr     => fun _ => fct3_CSRRSI
  | CSRRCI_32Zicsr     => fun _ => fct3_CSRRCI
  | CSRRW_64Zicsr      => fun _ => fct3_CSRRW
  | CSRRS_64Zicsr      => fun _ => fct3_CSRRS
  | CSRRC_64Zicsr      => fun _ => fct3_CSRRC
  | CSRRWI_64Zicsr     => fun _ => fct3_CSRRWI
  | CSRRSI_64Zicsr     => fun _ => fct3_CSRRSI
  | CSRRCI_64Zicsr     => fun _ => fct3_CSRRCI
  | MUL_32M            => fun _ => fct3_MUL
  | MULH_32M           => fun _ => fct3_MULH
  | MULHSU_32M         => fun _ => fct3_MULHSU
  | MULHU_32M          => fun _ => fct3_MULHU
  | DIV_32M            => fun _ => fct3_DIV
  | DIVU_32M           => fun _ => fct3_DIVU
  | REM_32M            => fun _ => fct3_REM
  | REMU_32M           => fun _ => fct3_REMU
  | MUL_64M            => fun _ => fct3_MUL
  | MULH_64M           => fun _ => fct3_MULH
  | MULHSU_64M         => fun _ => fct3_MULHSU
  | MULHU_64M          => fun _ => fct3_MULHU
  | DIV_64M            => fun _ => fct3_DIV
  | DIVU_64M           => fun _ => fct3_DIVU
  | REM_64M            => fun _ => fct3_REM
  | REMU_64M           => fun _ => fct3_REMU
  | MULW_64M           => fun _ => fct3_MULW
  | DIVW_64M           => fun _ => fct3_DIVW
  | DIVUW_64M          => fun _ => fct3_DIVUW
  | REMW_64M           => fun _ => fct3_REMW
  | REMUW_64M          => fun _ => fct3_REMUW
  | LR_W_00_32A        => fun _ => fct3_AW
  | LR_W_01_32A        => fun _ => fct3_AW
  | LR_W_10_32A        => fun _ => fct3_AW
  | LR_W_11_32A        => fun _ => fct3_AW
  | SC_W_00_32A        => fun _ => fct3_AW
  | SC_W_01_32A        => fun _ => fct3_AW
  | SC_W_10_32A        => fun _ => fct3_AW
  | SC_W_11_32A        => fun _ => fct3_AW
  | AMOSWAP_W_00_32A   => fun _ => fct3_AW
  | AMOSWAP_W_01_32A   => fun _ => fct3_AW
  | AMOSWAP_W_10_32A   => fun _ => fct3_AW
  | AMOSWAP_W_11_32A   => fun _ => fct3_AW
  | AMOADD_W_00_32A    => fun _ => fct3_AW
  | AMOADD_W_01_32A    => fun _ => fct3_AW
  | AMOADD_W_10_32A    => fun _ => fct3_AW
  | AMOADD_W_11_32A    => fun _ => fct3_AW
  | AMOXOR_W_00_32A    => fun _ => fct3_AW
  | AMOXOR_W_01_32A    => fun _ => fct3_AW
  | AMOXOR_W_10_32A    => fun _ => fct3_AW
  | AMOXOR_W_11_32A    => fun _ => fct3_AW
  | AMOAND_W_00_32A    => fun _ => fct3_AW
  | AMOAND_W_01_32A    => fun _ => fct3_AW
  | AMOAND_W_10_32A    => fun _ => fct3_AW
  | AMOAND_W_11_32A    => fun _ => fct3_AW
  | AMOOR_W_00_32A     => fun _ => fct3_AW
  | AMOOR_W_01_32A     => fun _ => fct3_AW
  | AMOOR_W_10_32A     => fun _ => fct3_AW
  | AMOOR_W_11_32A     => fun _ => fct3_AW
  | AMOMIN_W_00_32A    => fun _ => fct3_AW
  | AMOMIN_W_01_32A    => fun _ => fct3_AW
  | AMOMIN_W_10_32A    => fun _ => fct3_AW
  | AMOMIN_W_11_32A    => fun _ => fct3_AW
  | AMOMAX_W_00_32A    => fun _ => fct3_AW
  | AMOMAX_W_01_32A    => fun _ => fct3_AW
  | AMOMAX_W_10_32A    => fun _ => fct3_AW
  | AMOMAX_W_11_32A    => fun _ => fct3_AW
  | AMOMINU_W_00_32A   => fun _ => fct3_AW
  | AMOMINU_W_01_32A   => fun _ => fct3_AW
  | AMOMINU_W_10_32A   => fun _ => fct3_AW
  | AMOMINU_W_11_32A   => fun _ => fct3_AW
  | AMOMAXU_W_00_32A   => fun _ => fct3_AW
  | AMOMAXU_W_01_32A   => fun _ => fct3_AW
  | AMOMAXU_W_10_32A   => fun _ => fct3_AW
  | AMOMAXU_W_11_32A   => fun _ => fct3_AW
  | LR_W_00_64A        => fun _ => fct3_AW
  | LR_W_01_64A        => fun _ => fct3_AW
  | LR_W_10_64A        => fun _ => fct3_AW
  | LR_W_11_64A        => fun _ => fct3_AW
  | SC_W_00_64A        => fun _ => fct3_AW
  | SC_W_01_64A        => fun _ => fct3_AW
  | SC_W_10_64A        => fun _ => fct3_AW
  | SC_W_11_64A        => fun _ => fct3_AW
  | AMOSWAP_W_00_64A   => fun _ => fct3_AW
  | AMOSWAP_W_01_64A   => fun _ => fct3_AW
  | AMOSWAP_W_10_64A   => fun _ => fct3_AW
  | AMOSWAP_W_11_64A   => fun _ => fct3_AW
  | AMOADD_W_00_64A    => fun _ => fct3_AW
  | AMOADD_W_01_64A    => fun _ => fct3_AW
  | AMOADD_W_10_64A    => fun _ => fct3_AW
  | AMOADD_W_11_64A    => fun _ => fct3_AW
  | AMOXOR_W_00_64A    => fun _ => fct3_AW
  | AMOXOR_W_01_64A    => fun _ => fct3_AW
  | AMOXOR_W_10_64A    => fun _ => fct3_AW
  | AMOXOR_W_11_64A    => fun _ => fct3_AW
  | AMOAND_W_00_64A    => fun _ => fct3_AW
  | AMOAND_W_01_64A    => fun _ => fct3_AW
  | AMOAND_W_10_64A    => fun _ => fct3_AW
  | AMOAND_W_11_64A    => fun _ => fct3_AW
  | AMOOR_W_00_64A     => fun _ => fct3_AW
  | AMOOR_W_01_64A     => fun _ => fct3_AW
  | AMOOR_W_10_64A     => fun _ => fct3_AW
  | AMOOR_W_11_64A     => fun _ => fct3_AW
  | AMOMIN_W_00_64A    => fun _ => fct3_AW
  | AMOMIN_W_01_64A    => fun _ => fct3_AW
  | AMOMIN_W_10_64A    => fun _ => fct3_AW
  | AMOMIN_W_11_64A    => fun _ => fct3_AW
  | AMOMAX_W_00_64A    => fun _ => fct3_AW
  | AMOMAX_W_01_64A    => fun _ => fct3_AW
  | AMOMAX_W_10_64A    => fun _ => fct3_AW
  | AMOMAX_W_11_64A    => fun _ => fct3_AW
  | AMOMINU_W_00_64A   => fun _ => fct3_AW
  | AMOMINU_W_01_64A   => fun _ => fct3_AW
  | AMOMINU_W_10_64A   => fun _ => fct3_AW
  | AMOMINU_W_11_64A   => fun _ => fct3_AW
  | AMOMAXU_W_00_64A   => fun _ => fct3_AW
  | AMOMAXU_W_01_64A   => fun _ => fct3_AW
  | AMOMAXU_W_10_64A   => fun _ => fct3_AW
  | AMOMAXU_W_11_64A   => fun _ => fct3_AW
  | LR_D_00_64A        => fun _ => fct3_AD
  | LR_D_01_64A        => fun _ => fct3_AD
  | LR_D_10_64A        => fun _ => fct3_AD
  | LR_D_11_64A        => fun _ => fct3_AD
  | SC_D_00_64A        => fun _ => fct3_AD
  | SC_D_01_64A        => fun _ => fct3_AD
  | SC_D_10_64A        => fun _ => fct3_AD
  | SC_D_11_64A        => fun _ => fct3_AD
  | AMOSWAP_D_00_64A   => fun _ => fct3_AD
  | AMOSWAP_D_01_64A   => fun _ => fct3_AD
  | AMOSWAP_D_10_64A   => fun _ => fct3_AD
  | AMOSWAP_D_11_64A   => fun _ => fct3_AD
  | AMOADD_D_00_64A    => fun _ => fct3_AD
  | AMOADD_D_01_64A    => fun _ => fct3_AD
  | AMOADD_D_10_64A    => fun _ => fct3_AD
  | AMOADD_D_11_64A    => fun _ => fct3_AD
  | AMOXOR_D_00_64A    => fun _ => fct3_AD
  | AMOXOR_D_01_64A    => fun _ => fct3_AD
  | AMOXOR_D_10_64A    => fun _ => fct3_AD
  | AMOXOR_D_11_64A    => fun _ => fct3_AD
  | AMOAND_D_00_64A    => fun _ => fct3_AD
  | AMOAND_D_01_64A    => fun _ => fct3_AD
  | AMOAND_D_10_64A    => fun _ => fct3_AD
  | AMOAND_D_11_64A    => fun _ => fct3_AD
  | AMOOR_D_00_64A     => fun _ => fct3_AD
  | AMOOR_D_01_64A     => fun _ => fct3_AD
  | AMOOR_D_10_64A     => fun _ => fct3_AD
  | AMOOR_D_11_64A     => fun _ => fct3_AD
  | AMOMIN_D_00_64A    => fun _ => fct3_AD
  | AMOMIN_D_01_64A    => fun _ => fct3_AD
  | AMOMIN_D_10_64A    => fun _ => fct3_AD
  | AMOMIN_D_11_64A    => fun _ => fct3_AD
  | AMOMAX_D_00_64A    => fun _ => fct3_AD
  | AMOMAX_D_01_64A    => fun _ => fct3_AD
  | AMOMAX_D_10_64A    => fun _ => fct3_AD
  | AMOMAX_D_11_64A    => fun _ => fct3_AD
  | AMOMINU_D_00_64A   => fun _ => fct3_AD
  | AMOMINU_D_01_64A   => fun _ => fct3_AD
  | AMOMINU_D_10_64A   => fun _ => fct3_AD
  | AMOMINU_D_11_64A   => fun _ => fct3_AD
  | AMOMAXU_D_00_64A   => fun _ => fct3_AD
  | AMOMAXU_D_01_64A   => fun _ => fct3_AD
  | AMOMAXU_D_10_64A   => fun _ => fct3_AD
  | AMOMAXU_D_11_64A   => fun _ => fct3_AD
  | FLW_32F            => fun _ => fct3_LSF
  | FSW_32F            => fun _ => fct3_LSF
  | FMADD_RNE_S_32F    => fun _ => fct3_RNE
  | FMADD_RTZ_S_32F    => fun _ => fct3_RTZ
  | FMADD_RDN_S_32F    => fun _ => fct3_RDN
  | FMADD_RUP_S_32F    => fun _ => fct3_RUP
  | FMADD_RMM_S_32F    => fun _ => fct3_RMM
  | FMADD_DYN_S_32F    => fun _ => fct3_DYN
  | FMSUB_RNE_S_32F    => fun _ => fct3_RNE
  | FMSUB_RTZ_S_32F    => fun _ => fct3_RTZ
  | FMSUB_RDN_S_32F    => fun _ => fct3_RDN
  | FMSUB_RUP_S_32F    => fun _ => fct3_RUP
  | FMSUB_RMM_S_32F    => fun _ => fct3_RMM
  | FMSUB_DYN_S_32F    => fun _ => fct3_DYN
  | FNMSUB_RNE_S_32F   => fun _ => fct3_RNE
  | FNMSUB_RTZ_S_32F   => fun _ => fct3_RTZ
  | FNMSUB_RDN_S_32F   => fun _ => fct3_RDN
  | FNMSUB_RUP_S_32F   => fun _ => fct3_RUP
  | FNMSUB_RMM_S_32F   => fun _ => fct3_RMM
  | FNMSUB_DYN_S_32F   => fun _ => fct3_DYN
  | FNMADD_RNE_S_32F   => fun _ => fct3_RNE
  | FNMADD_RTZ_S_32F   => fun _ => fct3_RTZ
  | FNMADD_RDN_S_32F   => fun _ => fct3_RDN
  | FNMADD_RUP_S_32F   => fun _ => fct3_RUP
  | FNMADD_RMM_S_32F   => fun _ => fct3_RMM
  | FNMADD_DYN_S_32F   => fun _ => fct3_DYN
  | FADD_RNE_S_32F     => fun _ => fct3_RNE
  | FADD_RTZ_S_32F     => fun _ => fct3_RTZ
  | FADD_RDN_S_32F     => fun _ => fct3_RDN
  | FADD_RUP_S_32F     => fun _ => fct3_RUP
  | FADD_RMM_S_32F     => fun _ => fct3_RMM
  | FADD_DYN_S_32F     => fun _ => fct3_DYN
  | FSUB_RNE_S_32F     => fun _ => fct3_RNE
  | FSUB_RTZ_S_32F     => fun _ => fct3_RTZ
  | FSUB_RDN_S_32F     => fun _ => fct3_RDN
  | FSUB_RUP_S_32F     => fun _ => fct3_RUP
  | FSUB_RMM_S_32F     => fun _ => fct3_RMM
  | FSUB_DYN_S_32F     => fun _ => fct3_DYN
  | FMUL_RNE_S_32F     => fun _ => fct3_RNE
  | FMUL_RTZ_S_32F     => fun _ => fct3_RTZ
  | FMUL_RDN_S_32F     => fun _ => fct3_RDN
  | FMUL_RUP_S_32F     => fun _ => fct3_RUP
  | FMUL_RMM_S_32F     => fun _ => fct3_RMM
  | FMUL_DYN_S_32F     => fun _ => fct3_DYN
  | FDIV_RNE_S_32F     => fun _ => fct3_RNE
  | FDIV_RTZ_S_32F     => fun _ => fct3_RTZ
  | FDIV_RDN_S_32F     => fun _ => fct3_RDN
  | FDIV_RUP_S_32F     => fun _ => fct3_RUP
  | FDIV_RMM_S_32F     => fun _ => fct3_RMM
  | FDIV_DYN_S_32F     => fun _ => fct3_DYN
  | FSQRT_RNE_S_32F    => fun _ => fct3_RNE
  | FSQRT_RTZ_S_32F    => fun _ => fct3_RTZ
  | FSQRT_RDN_S_32F    => fun _ => fct3_RDN
  | FSQRT_RUP_S_32F    => fun _ => fct3_RUP
  | FSQRT_RMM_S_32F    => fun _ => fct3_RMM
  | FSQRT_DYN_S_32F    => fun _ => fct3_DYN
  | FSGNJ_S_32F        => fun _ => fct3_FSGNJ
  | FSGNJN_S_32F       => fun _ => fct3_FSGNJN
  | FSGNJX_S_32F       => fun _ => fct3_FSGNJX
  | FMIN_S_32F         => fun _ => fct3_FMIN
  | FMAX_S_32F         => fun _ => fct3_FMAX
  | FCVT_RNE_W_S_32F   => fun _ => fct3_RNE
  | FCVT_RTZ_W_S_32F   => fun _ => fct3_RTZ
  | FCVT_RDN_W_S_32F   => fun _ => fct3_RDN
  | FCVT_RUP_W_S_32F   => fun _ => fct3_RUP
  | FCVT_RMM_W_S_32F   => fun _ => fct3_RMM
  | FCVT_DYN_W_S_32F   => fun _ => fct3_DYN
  | FCVT_RNE_WU_S_32F  => fun _ => fct3_RNE
  | FCVT_RTZ_WU_S_32F  => fun _ => fct3_RTZ
  | FCVT_RDN_WU_S_32F  => fun _ => fct3_RDN
  | FCVT_RUP_WU_S_32F  => fun _ => fct3_RUP
  | FCVT_RMM_WU_S_32F  => fun _ => fct3_RMM
  | FCVT_DYN_WU_S_32F  => fun _ => fct3_DYN
  | FMV_X_W_32F        => fun _ => fct3_FMV
  | FEQ_S_32F          => fun _ => fct3_FEQ
  | FLT_S_32F          => fun _ => fct3_FLT
  | FLE_S_32F          => fun _ => fct3_FLE
  | FCLASS_S_32F       => fun _ => fct3_FCLASS
  | FCVT_RNE_S_W_32F   => fun _ => fct3_RNE
  | FCVT_RTZ_S_W_32F   => fun _ => fct3_RTZ
  | FCVT_RDN_S_W_32F   => fun _ => fct3_RDN
  | FCVT_RUP_S_W_32F   => fun _ => fct3_RUP
  | FCVT_RMM_S_W_32F   => fun _ => fct3_RMM
  | FCVT_DYN_S_W_32F   => fun _ => fct3_DYN
  | FCVT_RNE_S_WU_32F  => fun _ => fct3_RNE
  | FCVT_RTZ_S_WU_32F  => fun _ => fct3_RTZ
  | FCVT_RDN_S_WU_32F  => fun _ => fct3_RDN
  | FCVT_RUP_S_WU_32F  => fun _ => fct3_RUP
  | FCVT_RMM_S_WU_32F  => fun _ => fct3_RMM
  | FCVT_DYN_S_WU_32F  => fun _ => fct3_DYN
  | FMV_W_X_32F        => fun _ => fct3_FMV
  | FLW_64F            => fun _ => fct3_LSF
  | FSW_64F            => fun _ => fct3_LSF
  | FMADD_RNE_S_64F    => fun _ => fct3_RNE
  | FMADD_RTZ_S_64F    => fun _ => fct3_RTZ
  | FMADD_RDN_S_64F    => fun _ => fct3_RDN
  | FMADD_RUP_S_64F    => fun _ => fct3_RUP
  | FMADD_RMM_S_64F    => fun _ => fct3_RMM
  | FMADD_DYN_S_64F    => fun _ => fct3_DYN
  | FMSUB_RNE_S_64F    => fun _ => fct3_RNE
  | FMSUB_RTZ_S_64F    => fun _ => fct3_RTZ
  | FMSUB_RDN_S_64F    => fun _ => fct3_RDN
  | FMSUB_RUP_S_64F    => fun _ => fct3_RUP
  | FMSUB_RMM_S_64F    => fun _ => fct3_RMM
  | FMSUB_DYN_S_64F    => fun _ => fct3_DYN
  | FNMSUB_RNE_S_64F   => fun _ => fct3_RNE
  | FNMSUB_RTZ_S_64F   => fun _ => fct3_RTZ
  | FNMSUB_RDN_S_64F   => fun _ => fct3_RDN
  | FNMSUB_RUP_S_64F   => fun _ => fct3_RUP
  | FNMSUB_RMM_S_64F   => fun _ => fct3_RMM
  | FNMSUB_DYN_S_64F   => fun _ => fct3_DYN
  | FNMADD_RNE_S_64F   => fun _ => fct3_RNE
  | FNMADD_RTZ_S_64F   => fun _ => fct3_RTZ
  | FNMADD_RDN_S_64F   => fun _ => fct3_RDN
  | FNMADD_RUP_S_64F   => fun _ => fct3_RUP
  | FNMADD_RMM_S_64F   => fun _ => fct3_RMM
  | FNMADD_DYN_S_64F   => fun _ => fct3_DYN
  | FADD_RNE_S_64F     => fun _ => fct3_RNE
  | FADD_RTZ_S_64F     => fun _ => fct3_RTZ
  | FADD_RDN_S_64F     => fun _ => fct3_RDN
  | FADD_RUP_S_64F     => fun _ => fct3_RUP
  | FADD_RMM_S_64F     => fun _ => fct3_RMM
  | FADD_DYN_S_64F     => fun _ => fct3_DYN
  | FSUB_RNE_S_64F     => fun _ => fct3_RNE
  | FSUB_RTZ_S_64F     => fun _ => fct3_RTZ
  | FSUB_RDN_S_64F     => fun _ => fct3_RDN
  | FSUB_RUP_S_64F     => fun _ => fct3_RUP
  | FSUB_RMM_S_64F     => fun _ => fct3_RMM
  | FSUB_DYN_S_64F     => fun _ => fct3_DYN
  | FMUL_RNE_S_64F     => fun _ => fct3_RNE
  | FMUL_RTZ_S_64F     => fun _ => fct3_RTZ
  | FMUL_RDN_S_64F     => fun _ => fct3_RDN
  | FMUL_RUP_S_64F     => fun _ => fct3_RUP
  | FMUL_RMM_S_64F     => fun _ => fct3_RMM
  | FMUL_DYN_S_64F     => fun _ => fct3_DYN
  | FDIV_RNE_S_64F     => fun _ => fct3_RNE
  | FDIV_RTZ_S_64F     => fun _ => fct3_RTZ
  | FDIV_RDN_S_64F     => fun _ => fct3_RDN
  | FDIV_RUP_S_64F     => fun _ => fct3_RUP
  | FDIV_RMM_S_64F     => fun _ => fct3_RMM
  | FDIV_DYN_S_64F     => fun _ => fct3_DYN
  | FSQRT_RNE_S_64F    => fun _ => fct3_RNE
  | FSQRT_RTZ_S_64F    => fun _ => fct3_RTZ
  | FSQRT_RDN_S_64F    => fun _ => fct3_RDN
  | FSQRT_RUP_S_64F    => fun _ => fct3_RUP
  | FSQRT_RMM_S_64F    => fun _ => fct3_RMM
  | FSQRT_DYN_S_64F    => fun _ => fct3_DYN
  | FSGNJ_S_64F        => fun _ => fct3_FSGNJ
  | FSGNJN_S_64F       => fun _ => fct3_FSGNJN
  | FSGNJX_S_64F       => fun _ => fct3_FSGNJX
  | FMIN_S_64F         => fun _ => fct3_FMIN
  | FMAX_S_64F         => fun _ => fct3_FMAX
  | FCVT_RNE_W_S_64F   => fun _ => fct3_RNE
  | FCVT_RTZ_W_S_64F   => fun _ => fct3_RTZ
  | FCVT_RDN_W_S_64F   => fun _ => fct3_RDN
  | FCVT_RUP_W_S_64F   => fun _ => fct3_RUP
  | FCVT_RMM_W_S_64F   => fun _ => fct3_RMM
  | FCVT_DYN_W_S_64F   => fun _ => fct3_DYN
  | FCVT_RNE_WU_S_64F  => fun _ => fct3_RNE
  | FCVT_RTZ_WU_S_64F  => fun _ => fct3_RTZ
  | FCVT_RDN_WU_S_64F  => fun _ => fct3_RDN
  | FCVT_RUP_WU_S_64F  => fun _ => fct3_RUP
  | FCVT_RMM_WU_S_64F  => fun _ => fct3_RMM
  | FCVT_DYN_WU_S_64F  => fun _ => fct3_DYN
  | FMV_X_W_64F        => fun _ => fct3_FMV
  | FEQ_S_64F          => fun _ => fct3_FEQ
  | FLT_S_64F          => fun _ => fct3_FLT
  | FLE_S_64F          => fun _ => fct3_FLE
  | FCLASS_S_64F       => fun _ => fct3_FCLASS
  | FCVT_RNE_S_W_64F   => fun _ => fct3_RNE
  | FCVT_RTZ_S_W_64F   => fun _ => fct3_RTZ
  | FCVT_RDN_S_W_64F   => fun _ => fct3_RDN
  | FCVT_RUP_S_W_64F   => fun _ => fct3_RUP
  | FCVT_RMM_S_W_64F   => fun _ => fct3_RMM
  | FCVT_DYN_S_W_64F   => fun _ => fct3_DYN
  | FCVT_RNE_S_WU_64F  => fun _ => fct3_RNE
  | FCVT_RTZ_S_WU_64F  => fun _ => fct3_RTZ
  | FCVT_RDN_S_WU_64F  => fun _ => fct3_RDN
  | FCVT_RUP_S_WU_64F  => fun _ => fct3_RUP
  | FCVT_RMM_S_WU_64F  => fun _ => fct3_RMM
  | FCVT_DYN_S_WU_64F  => fun _ => fct3_DYN
  | FMV_W_X_64F        => fun _ => fct3_FMV
  | FCVT_RNE_L_S_64F   => fun _ => fct3_RNE
  | FCVT_RTZ_L_S_64F   => fun _ => fct3_RTZ
  | FCVT_RDN_L_S_64F   => fun _ => fct3_RDN
  | FCVT_RUP_L_S_64F   => fun _ => fct3_RUP
  | FCVT_RMM_L_S_64F   => fun _ => fct3_RMM
  | FCVT_DYN_L_S_64F   => fun _ => fct3_DYN
  | FCVT_RNE_LU_S_64F  => fun _ => fct3_RNE
  | FCVT_RTZ_LU_S_64F  => fun _ => fct3_RTZ
  | FCVT_RDN_LU_S_64F  => fun _ => fct3_RDN
  | FCVT_RUP_LU_S_64F  => fun _ => fct3_RUP
  | FCVT_RMM_LU_S_64F  => fun _ => fct3_RMM
  | FCVT_DYN_LU_S_64F  => fun _ => fct3_DYN
  | FCVT_RNE_S_L_64F   => fun _ => fct3_RNE
  | FCVT_RTZ_S_L_64F   => fun _ => fct3_RTZ
  | FCVT_RDN_S_L_64F   => fun _ => fct3_RDN
  | FCVT_RUP_S_L_64F   => fun _ => fct3_RUP
  | FCVT_RMM_S_L_64F   => fun _ => fct3_RMM
  | FCVT_DYN_S_L_64F   => fun _ => fct3_DYN
  | FCVT_RNE_S_LU_64F  => fun _ => fct3_RNE
  | FCVT_RTZ_S_LU_64F  => fun _ => fct3_RTZ
  | FCVT_RDN_S_LU_64F  => fun _ => fct3_RDN
  | FCVT_RUP_S_LU_64F  => fun _ => fct3_RUP
  | FCVT_RMM_S_LU_64F  => fun _ => fct3_RMM
  | FCVT_DYN_S_LU_64F  => fun _ => fct3_DYN
  | FLD_32D            => fun _ => fct3_LSD
  | FSD_32D            => fun _ => fct3_LSD
  | FMADD_RNE_D_32D    => fun _ => fct3_RNE
  | FMADD_RTZ_D_32D    => fun _ => fct3_RTZ
  | FMADD_RDN_D_32D    => fun _ => fct3_RDN
  | FMADD_RUP_D_32D    => fun _ => fct3_RUP
  | FMADD_RMM_D_32D    => fun _ => fct3_RMM
  | FMADD_DYN_D_32D    => fun _ => fct3_DYN
  | FMSUB_RNE_D_32D    => fun _ => fct3_RNE
  | FMSUB_RTZ_D_32D    => fun _ => fct3_RTZ
  | FMSUB_RDN_D_32D    => fun _ => fct3_RDN
  | FMSUB_RUP_D_32D    => fun _ => fct3_RUP
  | FMSUB_RMM_D_32D    => fun _ => fct3_RMM
  | FMSUB_DYN_D_32D    => fun _ => fct3_DYN
  | FNMSUB_RNE_D_32D   => fun _ => fct3_RNE
  | FNMSUB_RTZ_D_32D   => fun _ => fct3_RTZ
  | FNMSUB_RDN_D_32D   => fun _ => fct3_RDN
  | FNMSUB_RUP_D_32D   => fun _ => fct3_RUP
  | FNMSUB_RMM_D_32D   => fun _ => fct3_RMM
  | FNMSUB_DYN_D_32D   => fun _ => fct3_DYN
  | FNMADD_RNE_D_32D   => fun _ => fct3_RNE
  | FNMADD_RTZ_D_32D   => fun _ => fct3_RTZ
  | FNMADD_RDN_D_32D   => fun _ => fct3_RDN
  | FNMADD_RUP_D_32D   => fun _ => fct3_RUP
  | FNMADD_RMM_D_32D   => fun _ => fct3_RMM
  | FNMADD_DYN_D_32D   => fun _ => fct3_DYN
  | FADD_RNE_D_32D     => fun _ => fct3_RNE
  | FADD_RTZ_D_32D     => fun _ => fct3_RTZ
  | FADD_RDN_D_32D     => fun _ => fct3_RDN
  | FADD_RUP_D_32D     => fun _ => fct3_RUP
  | FADD_RMM_D_32D     => fun _ => fct3_RMM
  | FADD_DYN_D_32D     => fun _ => fct3_DYN
  | FSUB_RNE_D_32D     => fun _ => fct3_RNE
  | FSUB_RTZ_D_32D     => fun _ => fct3_RTZ
  | FSUB_RDN_D_32D     => fun _ => fct3_RDN
  | FSUB_RUP_D_32D     => fun _ => fct3_RUP
  | FSUB_RMM_D_32D     => fun _ => fct3_RMM
  | FSUB_DYN_D_32D     => fun _ => fct3_DYN
  | FMUL_RNE_D_32D     => fun _ => fct3_RNE
  | FMUL_RTZ_D_32D     => fun _ => fct3_RTZ
  | FMUL_RDN_D_32D     => fun _ => fct3_RDN
  | FMUL_RUP_D_32D     => fun _ => fct3_RUP
  | FMUL_RMM_D_32D     => fun _ => fct3_RMM
  | FMUL_DYN_D_32D     => fun _ => fct3_DYN
  | FDIV_RNE_D_32D     => fun _ => fct3_RNE
  | FDIV_RTZ_D_32D     => fun _ => fct3_RTZ
  | FDIV_RDN_D_32D     => fun _ => fct3_RDN
  | FDIV_RUP_D_32D     => fun _ => fct3_RUP
  | FDIV_RMM_D_32D     => fun _ => fct3_RMM
  | FDIV_DYN_D_32D     => fun _ => fct3_DYN
  | FSQRT_RNE_D_32D    => fun _ => fct3_RNE
  | FSQRT_RTZ_D_32D    => fun _ => fct3_RTZ
  | FSQRT_RDN_D_32D    => fun _ => fct3_RDN
  | FSQRT_RUP_D_32D    => fun _ => fct3_RUP
  | FSQRT_RMM_D_32D    => fun _ => fct3_RMM
  | FSQRT_DYN_D_32D    => fun _ => fct3_DYN
  | FSGNJ_D_32D        => fun _ => fct3_FSGNJ
  | FSGNJN_D_32D       => fun _ => fct3_FSGNJN
  | FSGNJX_D_32D       => fun _ => fct3_FSGNJX
  | FMIN_D_32D         => fun _ => fct3_FMIN
  | FMAX_D_32D         => fun _ => fct3_FMAX
  | FCVT_RNE_S_D_32D   => fun _ => fct3_RNE
  | FCVT_RTZ_S_D_32D   => fun _ => fct3_RTZ
  | FCVT_RDN_S_D_32D   => fun _ => fct3_RDN
  | FCVT_RUP_S_D_32D   => fun _ => fct3_RUP
  | FCVT_RMM_S_D_32D   => fun _ => fct3_RMM
  | FCVT_DYN_S_D_32D   => fun _ => fct3_DYN
  | FCVT_RNE_D_S_32D   => fun _ => fct3_RNE
  | FCVT_RTZ_D_S_32D   => fun _ => fct3_RTZ
  | FCVT_RDN_D_S_32D   => fun _ => fct3_RDN
  | FCVT_RUP_D_S_32D   => fun _ => fct3_RUP
  | FCVT_RMM_D_S_32D   => fun _ => fct3_RMM
  | FCVT_DYN_D_S_32D   => fun _ => fct3_DYN
  | FEQ_D_32D          => fun _ => fct3_FEQ
  | FLT_D_32D          => fun _ => fct3_FLT
  | FLE_D_32D          => fun _ => fct3_FLE
  | FCLASS_D_32D       => fun _ => fct3_FCLASS
  | FCVT_RNE_W_D_32D   => fun _ => fct3_RNE
  | FCVT_RTZ_W_D_32D   => fun _ => fct3_RTZ
  | FCVT_RDN_W_D_32D   => fun _ => fct3_RDN
  | FCVT_RUP_W_D_32D   => fun _ => fct3_RUP
  | FCVT_RMM_W_D_32D   => fun _ => fct3_RMM
  | FCVT_DYN_W_D_32D   => fun _ => fct3_DYN
  | FCVT_RNE_WU_D_32D  => fun _ => fct3_RNE
  | FCVT_RTZ_WU_D_32D  => fun _ => fct3_RTZ
  | FCVT_RDN_WU_D_32D  => fun _ => fct3_RDN
  | FCVT_RUP_WU_D_32D  => fun _ => fct3_RUP
  | FCVT_RMM_WU_D_32D  => fun _ => fct3_RMM
  | FCVT_DYN_WU_D_32D  => fun _ => fct3_DYN
  | FCVT_RNE_D_W_32D   => fun _ => fct3_RNE
  | FCVT_RTZ_D_W_32D   => fun _ => fct3_RTZ
  | FCVT_RDN_D_W_32D   => fun _ => fct3_RDN
  | FCVT_RUP_D_W_32D   => fun _ => fct3_RUP
  | FCVT_RMM_D_W_32D   => fun _ => fct3_RMM
  | FCVT_DYN_D_W_32D   => fun _ => fct3_DYN
  | FCVT_RNE_D_WU_32D  => fun _ => fct3_RNE
  | FCVT_RTZ_D_WU_32D  => fun _ => fct3_RTZ
  | FCVT_RDN_D_WU_32D  => fun _ => fct3_RDN
  | FCVT_RUP_D_WU_32D  => fun _ => fct3_RUP
  | FCVT_RMM_D_WU_32D  => fun _ => fct3_RMM
  | FCVT_DYN_D_WU_32D  => fun _ => fct3_DYN
  | FLD_64D            => fun _ => fct3_LSD
  | FSD_64D            => fun _ => fct3_LSD
  | FMADD_RNE_D_64D    => fun _ => fct3_RNE
  | FMADD_RTZ_D_64D    => fun _ => fct3_RTZ
  | FMADD_RDN_D_64D    => fun _ => fct3_RDN
  | FMADD_RUP_D_64D    => fun _ => fct3_RUP
  | FMADD_RMM_D_64D    => fun _ => fct3_RMM
  | FMADD_DYN_D_64D    => fun _ => fct3_DYN
  | FMSUB_RNE_D_64D    => fun _ => fct3_RNE
  | FMSUB_RTZ_D_64D    => fun _ => fct3_RTZ
  | FMSUB_RDN_D_64D    => fun _ => fct3_RDN
  | FMSUB_RUP_D_64D    => fun _ => fct3_RUP
  | FMSUB_RMM_D_64D    => fun _ => fct3_RMM
  | FMSUB_DYN_D_64D    => fun _ => fct3_DYN
  | FNMSUB_RNE_D_64D   => fun _ => fct3_RNE
  | FNMSUB_RTZ_D_64D   => fun _ => fct3_RTZ
  | FNMSUB_RDN_D_64D   => fun _ => fct3_RDN
  | FNMSUB_RUP_D_64D   => fun _ => fct3_RUP
  | FNMSUB_RMM_D_64D   => fun _ => fct3_RMM
  | FNMSUB_DYN_D_64D   => fun _ => fct3_DYN
  | FNMADD_RNE_D_64D   => fun _ => fct3_RNE
  | FNMADD_RTZ_D_64D   => fun _ => fct3_RTZ
  | FNMADD_RDN_D_64D   => fun _ => fct3_RDN
  | FNMADD_RUP_D_64D   => fun _ => fct3_RUP
  | FNMADD_RMM_D_64D   => fun _ => fct3_RMM
  | FNMADD_DYN_D_64D   => fun _ => fct3_DYN
  | FADD_RNE_D_64D     => fun _ => fct3_RNE
  | FADD_RTZ_D_64D     => fun _ => fct3_RTZ
  | FADD_RDN_D_64D     => fun _ => fct3_RDN
  | FADD_RUP_D_64D     => fun _ => fct3_RUP
  | FADD_RMM_D_64D     => fun _ => fct3_RMM
  | FADD_DYN_D_64D     => fun _ => fct3_DYN
  | FSUB_RNE_D_64D     => fun _ => fct3_RNE
  | FSUB_RTZ_D_64D     => fun _ => fct3_RTZ
  | FSUB_RDN_D_64D     => fun _ => fct3_RDN
  | FSUB_RUP_D_64D     => fun _ => fct3_RUP
  | FSUB_RMM_D_64D     => fun _ => fct3_RMM
  | FSUB_DYN_D_64D     => fun _ => fct3_DYN
  | FMUL_RNE_D_64D     => fun _ => fct3_RNE
  | FMUL_RTZ_D_64D     => fun _ => fct3_RTZ
  | FMUL_RDN_D_64D     => fun _ => fct3_RDN
  | FMUL_RUP_D_64D     => fun _ => fct3_RUP
  | FMUL_RMM_D_64D     => fun _ => fct3_RMM
  | FMUL_DYN_D_64D     => fun _ => fct3_DYN
  | FDIV_RNE_D_64D     => fun _ => fct3_RNE
  | FDIV_RTZ_D_64D     => fun _ => fct3_RTZ
  | FDIV_RDN_D_64D     => fun _ => fct3_RDN
  | FDIV_RUP_D_64D     => fun _ => fct3_RUP
  | FDIV_RMM_D_64D     => fun _ => fct3_RMM
  | FDIV_DYN_D_64D     => fun _ => fct3_DYN
  | FSQRT_RNE_D_64D    => fun _ => fct3_RNE
  | FSQRT_RTZ_D_64D    => fun _ => fct3_RTZ
  | FSQRT_RDN_D_64D    => fun _ => fct3_RDN
  | FSQRT_RUP_D_64D    => fun _ => fct3_RUP
  | FSQRT_RMM_D_64D    => fun _ => fct3_RMM
  | FSQRT_DYN_D_64D    => fun _ => fct3_DYN
  | FSGNJ_D_64D        => fun _ => fct3_FSGNJ
  | FSGNJN_D_64D       => fun _ => fct3_FSGNJN
  | FSGNJX_D_64D       => fun _ => fct3_FSGNJX
  | FMIN_D_64D         => fun _ => fct3_FMIN
  | FMAX_D_64D         => fun _ => fct3_FMAX
  | FCVT_RNE_S_D_64D   => fun _ => fct3_RNE
  | FCVT_RTZ_S_D_64D   => fun _ => fct3_RTZ
  | FCVT_RDN_S_D_64D   => fun _ => fct3_RDN
  | FCVT_RUP_S_D_64D   => fun _ => fct3_RUP
  | FCVT_RMM_S_D_64D   => fun _ => fct3_RMM
  | FCVT_DYN_S_D_64D   => fun _ => fct3_DYN
  | FCVT_RNE_D_S_64D   => fun _ => fct3_RNE
  | FCVT_RTZ_D_S_64D   => fun _ => fct3_RTZ
  | FCVT_RDN_D_S_64D   => fun _ => fct3_RDN
  | FCVT_RUP_D_S_64D   => fun _ => fct3_RUP
  | FCVT_RMM_D_S_64D   => fun _ => fct3_RMM
  | FCVT_DYN_D_S_64D   => fun _ => fct3_DYN
  | FEQ_D_64D          => fun _ => fct3_FEQ
  | FLT_D_64D          => fun _ => fct3_FLT
  | FLE_D_64D          => fun _ => fct3_FLE
  | FCLASS_D_64D       => fun _ => fct3_FCLASS
  | FCVT_RNE_W_D_64D   => fun _ => fct3_RNE
  | FCVT_RTZ_W_D_64D   => fun _ => fct3_RTZ
  | FCVT_RDN_W_D_64D   => fun _ => fct3_RDN
  | FCVT_RUP_W_D_64D   => fun _ => fct3_RUP
  | FCVT_RMM_W_D_64D   => fun _ => fct3_RMM
  | FCVT_DYN_W_D_64D   => fun _ => fct3_DYN
  | FCVT_RNE_WU_D_64D  => fun _ => fct3_RNE
  | FCVT_RTZ_WU_D_64D  => fun _ => fct3_RTZ
  | FCVT_RDN_WU_D_64D  => fun _ => fct3_RDN
  | FCVT_RUP_WU_D_64D  => fun _ => fct3_RUP
  | FCVT_RMM_WU_D_64D  => fun _ => fct3_RMM
  | FCVT_DYN_WU_D_64D  => fun _ => fct3_DYN
  | FCVT_RNE_D_W_64D   => fun _ => fct3_RNE
  | FCVT_RTZ_D_W_64D   => fun _ => fct3_RTZ
  | FCVT_RDN_D_W_64D   => fun _ => fct3_RDN
  | FCVT_RUP_D_W_64D   => fun _ => fct3_RUP
  | FCVT_RMM_D_W_64D   => fun _ => fct3_RMM
  | FCVT_DYN_D_W_64D   => fun _ => fct3_DYN
  | FCVT_RNE_D_WU_64D  => fun _ => fct3_RNE
  | FCVT_RTZ_D_WU_64D  => fun _ => fct3_RTZ
  | FCVT_RDN_D_WU_64D  => fun _ => fct3_RDN
  | FCVT_RUP_D_WU_64D  => fun _ => fct3_RUP
  | FCVT_RMM_D_WU_64D  => fun _ => fct3_RMM
  | FCVT_DYN_D_WU_64D  => fun _ => fct3_DYN
  | FCVT_RNE_L_D_64D   => fun _ => fct3_RNE
  | FCVT_RTZ_L_D_64D   => fun _ => fct3_RTZ
  | FCVT_RDN_L_D_64D   => fun _ => fct3_RDN
  | FCVT_RUP_L_D_64D   => fun _ => fct3_RUP
  | FCVT_RMM_L_D_64D   => fun _ => fct3_RMM
  | FCVT_DYN_L_D_64D   => fun _ => fct3_DYN
  | FCVT_RNE_LU_D_64D  => fun _ => fct3_RNE
  | FCVT_RTZ_LU_D_64D  => fun _ => fct3_RTZ
  | FCVT_RDN_LU_D_64D  => fun _ => fct3_RDN
  | FCVT_RUP_LU_D_64D  => fun _ => fct3_RUP
  | FCVT_RMM_LU_D_64D  => fun _ => fct3_RMM
  | FCVT_DYN_LU_D_64D  => fun _ => fct3_DYN
  | FMV_X_D_64D        => fun _ => fct3_FMV
  | FCVT_RNE_D_L_64D   => fun _ => fct3_RNE
  | FCVT_RTZ_D_L_64D   => fun _ => fct3_RTZ
  | FCVT_RDN_D_L_64D   => fun _ => fct3_RDN
  | FCVT_RUP_D_L_64D   => fun _ => fct3_RUP
  | FCVT_RMM_D_L_64D   => fun _ => fct3_RMM
  | FCVT_DYN_D_L_64D   => fun _ => fct3_DYN
  | FCVT_RNE_D_LU_64D  => fun _ => fct3_RNE
  | FCVT_RTZ_D_LU_64D  => fun _ => fct3_RTZ
  | FCVT_RDN_D_LU_64D  => fun _ => fct3_RDN
  | FCVT_RUP_D_LU_64D  => fun _ => fct3_RUP
  | FCVT_RMM_D_LU_64D  => fun _ => fct3_RMM
  | FCVT_DYN_D_LU_64D  => fun _ => fct3_DYN
  | FMV_D_X_64D        => fun _ => fct3_FMV
  | FLQ_32Q            => fun _ => fct3_LSQ
  | FSQ_32Q            => fun _ => fct3_LSQ
  | FMADD_RNE_Q_32Q    => fun _ => fct3_RNE
  | FMADD_RTZ_Q_32Q    => fun _ => fct3_RTZ
  | FMADD_RDN_Q_32Q    => fun _ => fct3_RDN
  | FMADD_RUP_Q_32Q    => fun _ => fct3_RUP
  | FMADD_RMM_Q_32Q    => fun _ => fct3_RMM
  | FMADD_DYN_Q_32Q    => fun _ => fct3_DYN
  | FMSUB_RNE_Q_32Q    => fun _ => fct3_RNE
  | FMSUB_RTZ_Q_32Q    => fun _ => fct3_RTZ
  | FMSUB_RDN_Q_32Q    => fun _ => fct3_RDN
  | FMSUB_RUP_Q_32Q    => fun _ => fct3_RUP
  | FMSUB_RMM_Q_32Q    => fun _ => fct3_RMM
  | FMSUB_DYN_Q_32Q    => fun _ => fct3_DYN
  | FNMSUB_RNE_Q_32Q   => fun _ => fct3_RNE
  | FNMSUB_RTZ_Q_32Q   => fun _ => fct3_RTZ
  | FNMSUB_RDN_Q_32Q   => fun _ => fct3_RDN
  | FNMSUB_RUP_Q_32Q   => fun _ => fct3_RUP
  | FNMSUB_RMM_Q_32Q   => fun _ => fct3_RMM
  | FNMSUB_DYN_Q_32Q   => fun _ => fct3_DYN
  | FNMADD_RNE_Q_32Q   => fun _ => fct3_RNE
  | FNMADD_RTZ_Q_32Q   => fun _ => fct3_RTZ
  | FNMADD_RDN_Q_32Q   => fun _ => fct3_RDN
  | FNMADD_RUP_Q_32Q   => fun _ => fct3_RUP
  | FNMADD_RMM_Q_32Q   => fun _ => fct3_RMM
  | FNMADD_DYN_Q_32Q   => fun _ => fct3_DYN
  | FADD_RNE_Q_32Q     => fun _ => fct3_RNE
  | FADD_RTZ_Q_32Q     => fun _ => fct3_RTZ
  | FADD_RDN_Q_32Q     => fun _ => fct3_RDN
  | FADD_RUP_Q_32Q     => fun _ => fct3_RUP
  | FADD_RMM_Q_32Q     => fun _ => fct3_RMM
  | FADD_DYN_Q_32Q     => fun _ => fct3_DYN
  | FSUB_RNE_Q_32Q     => fun _ => fct3_RNE
  | FSUB_RTZ_Q_32Q     => fun _ => fct3_RTZ
  | FSUB_RDN_Q_32Q     => fun _ => fct3_RDN
  | FSUB_RUP_Q_32Q     => fun _ => fct3_RUP
  | FSUB_RMM_Q_32Q     => fun _ => fct3_RMM
  | FSUB_DYN_Q_32Q     => fun _ => fct3_DYN
  | FMUL_RNE_Q_32Q     => fun _ => fct3_RNE
  | FMUL_RTZ_Q_32Q     => fun _ => fct3_RTZ
  | FMUL_RDN_Q_32Q     => fun _ => fct3_RDN
  | FMUL_RUP_Q_32Q     => fun _ => fct3_RUP
  | FMUL_RMM_Q_32Q     => fun _ => fct3_RMM
  | FMUL_DYN_Q_32Q     => fun _ => fct3_DYN
  | FDIV_RNE_Q_32Q     => fun _ => fct3_RNE
  | FDIV_RTZ_Q_32Q     => fun _ => fct3_RTZ
  | FDIV_RDN_Q_32Q     => fun _ => fct3_RDN
  | FDIV_RUP_Q_32Q     => fun _ => fct3_RUP
  | FDIV_RMM_Q_32Q     => fun _ => fct3_RMM
  | FDIV_DYN_Q_32Q     => fun _ => fct3_DYN
  | FSQRT_RNE_Q_32Q    => fun _ => fct3_RNE
  | FSQRT_RTZ_Q_32Q    => fun _ => fct3_RTZ
  | FSQRT_RDN_Q_32Q    => fun _ => fct3_RDN
  | FSQRT_RUP_Q_32Q    => fun _ => fct3_RUP
  | FSQRT_RMM_Q_32Q    => fun _ => fct3_RMM
  | FSQRT_DYN_Q_32Q    => fun _ => fct3_DYN
  | FSGNJ_Q_32Q        => fun _ => fct3_FSGNJ
  | FSGNJN_Q_32Q       => fun _ => fct3_FSGNJN
  | FSGNJX_Q_32Q       => fun _ => fct3_FSGNJX
  | FMIN_Q_32Q         => fun _ => fct3_FMIN
  | FMAX_Q_32Q         => fun _ => fct3_FMAX
  | FCVT_RNE_S_Q_32Q   => fun _ => fct3_RNE
  | FCVT_RTZ_S_Q_32Q   => fun _ => fct3_RTZ
  | FCVT_RDN_S_Q_32Q   => fun _ => fct3_RDN
  | FCVT_RUP_S_Q_32Q   => fun _ => fct3_RUP
  | FCVT_RMM_S_Q_32Q   => fun _ => fct3_RMM
  | FCVT_DYN_S_Q_32Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_S_32Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_S_32Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_S_32Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_S_32Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_S_32Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_S_32Q   => fun _ => fct3_DYN
  | FCVT_RNE_D_Q_32Q   => fun _ => fct3_RNE
  | FCVT_RTZ_D_Q_32Q   => fun _ => fct3_RTZ
  | FCVT_RDN_D_Q_32Q   => fun _ => fct3_RDN
  | FCVT_RUP_D_Q_32Q   => fun _ => fct3_RUP
  | FCVT_RMM_D_Q_32Q   => fun _ => fct3_RMM
  | FCVT_DYN_D_Q_32Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_D_32Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_D_32Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_D_32Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_D_32Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_D_32Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_D_32Q   => fun _ => fct3_DYN
  | FEQ_Q_32Q          => fun _ => fct3_FEQ
  | FLT_Q_32Q          => fun _ => fct3_FLT
  | FLE_Q_32Q          => fun _ => fct3_FLE
  | FCLASS_Q_32Q       => fun _ => fct3_FCLASS
  | FCVT_RNE_W_Q_32Q   => fun _ => fct3_RNE
  | FCVT_RTZ_W_Q_32Q   => fun _ => fct3_RTZ
  | FCVT_RDN_W_Q_32Q   => fun _ => fct3_RDN
  | FCVT_RUP_W_Q_32Q   => fun _ => fct3_RUP
  | FCVT_RMM_W_Q_32Q   => fun _ => fct3_RMM
  | FCVT_DYN_W_Q_32Q   => fun _ => fct3_DYN
  | FCVT_RNE_WU_Q_32Q  => fun _ => fct3_RNE
  | FCVT_RTZ_WU_Q_32Q  => fun _ => fct3_RTZ
  | FCVT_RDN_WU_Q_32Q  => fun _ => fct3_RDN
  | FCVT_RUP_WU_Q_32Q  => fun _ => fct3_RUP
  | FCVT_RMM_WU_Q_32Q  => fun _ => fct3_RMM
  | FCVT_DYN_WU_Q_32Q  => fun _ => fct3_DYN
  | FCVT_RNE_Q_W_32Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_W_32Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_W_32Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_W_32Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_W_32Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_W_32Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_WU_32Q  => fun _ => fct3_RNE
  | FCVT_RTZ_Q_WU_32Q  => fun _ => fct3_RTZ
  | FCVT_RDN_Q_WU_32Q  => fun _ => fct3_RDN
  | FCVT_RUP_Q_WU_32Q  => fun _ => fct3_RUP
  | FCVT_RMM_Q_WU_32Q  => fun _ => fct3_RMM
  | FCVT_DYN_Q_WU_32Q  => fun _ => fct3_DYN
  | FLQ_64Q            => fun _ => fct3_LSQ
  | FSQ_64Q            => fun _ => fct3_LSQ
  | FMADD_RNE_Q_64Q    => fun _ => fct3_RNE
  | FMADD_RTZ_Q_64Q    => fun _ => fct3_RTZ
  | FMADD_RDN_Q_64Q    => fun _ => fct3_RDN
  | FMADD_RUP_Q_64Q    => fun _ => fct3_RUP
  | FMADD_RMM_Q_64Q    => fun _ => fct3_RMM
  | FMADD_DYN_Q_64Q    => fun _ => fct3_DYN
  | FMSUB_RNE_Q_64Q    => fun _ => fct3_RNE
  | FMSUB_RTZ_Q_64Q    => fun _ => fct3_RTZ
  | FMSUB_RDN_Q_64Q    => fun _ => fct3_RDN
  | FMSUB_RUP_Q_64Q    => fun _ => fct3_RUP
  | FMSUB_RMM_Q_64Q    => fun _ => fct3_RMM
  | FMSUB_DYN_Q_64Q    => fun _ => fct3_DYN
  | FNMSUB_RNE_Q_64Q   => fun _ => fct3_RNE
  | FNMSUB_RTZ_Q_64Q   => fun _ => fct3_RTZ
  | FNMSUB_RDN_Q_64Q   => fun _ => fct3_RDN
  | FNMSUB_RUP_Q_64Q   => fun _ => fct3_RUP
  | FNMSUB_RMM_Q_64Q   => fun _ => fct3_RMM
  | FNMSUB_DYN_Q_64Q   => fun _ => fct3_DYN
  | FNMADD_RNE_Q_64Q   => fun _ => fct3_RNE
  | FNMADD_RTZ_Q_64Q   => fun _ => fct3_RTZ
  | FNMADD_RDN_Q_64Q   => fun _ => fct3_RDN
  | FNMADD_RUP_Q_64Q   => fun _ => fct3_RUP
  | FNMADD_RMM_Q_64Q   => fun _ => fct3_RMM
  | FNMADD_DYN_Q_64Q   => fun _ => fct3_DYN
  | FADD_RNE_Q_64Q     => fun _ => fct3_RNE
  | FADD_RTZ_Q_64Q     => fun _ => fct3_RTZ
  | FADD_RDN_Q_64Q     => fun _ => fct3_RDN
  | FADD_RUP_Q_64Q     => fun _ => fct3_RUP
  | FADD_RMM_Q_64Q     => fun _ => fct3_RMM
  | FADD_DYN_Q_64Q     => fun _ => fct3_DYN
  | FSUB_RNE_Q_64Q     => fun _ => fct3_RNE
  | FSUB_RTZ_Q_64Q     => fun _ => fct3_RTZ
  | FSUB_RDN_Q_64Q     => fun _ => fct3_RDN
  | FSUB_RUP_Q_64Q     => fun _ => fct3_RUP
  | FSUB_RMM_Q_64Q     => fun _ => fct3_RMM
  | FSUB_DYN_Q_64Q     => fun _ => fct3_DYN
  | FMUL_RNE_Q_64Q     => fun _ => fct3_RNE
  | FMUL_RTZ_Q_64Q     => fun _ => fct3_RTZ
  | FMUL_RDN_Q_64Q     => fun _ => fct3_RDN
  | FMUL_RUP_Q_64Q     => fun _ => fct3_RUP
  | FMUL_RMM_Q_64Q     => fun _ => fct3_RMM
  | FMUL_DYN_Q_64Q     => fun _ => fct3_DYN
  | FDIV_RNE_Q_64Q     => fun _ => fct3_RNE
  | FDIV_RTZ_Q_64Q     => fun _ => fct3_RTZ
  | FDIV_RDN_Q_64Q     => fun _ => fct3_RDN
  | FDIV_RUP_Q_64Q     => fun _ => fct3_RUP
  | FDIV_RMM_Q_64Q     => fun _ => fct3_RMM
  | FDIV_DYN_Q_64Q     => fun _ => fct3_DYN
  | FSQRT_RNE_Q_64Q    => fun _ => fct3_RNE
  | FSQRT_RTZ_Q_64Q    => fun _ => fct3_RTZ
  | FSQRT_RDN_Q_64Q    => fun _ => fct3_RDN
  | FSQRT_RUP_Q_64Q    => fun _ => fct3_RUP
  | FSQRT_RMM_Q_64Q    => fun _ => fct3_RMM
  | FSQRT_DYN_Q_64Q    => fun _ => fct3_DYN
  | FSGNJ_Q_64Q        => fun _ => fct3_FSGNJ
  | FSGNJN_Q_64Q       => fun _ => fct3_FSGNJN
  | FSGNJX_Q_64Q       => fun _ => fct3_FSGNJX
  | FMIN_Q_64Q         => fun _ => fct3_FMIN
  | FMAX_Q_64Q         => fun _ => fct3_FMAX
  | FCVT_RNE_S_Q_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_S_Q_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_S_Q_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_S_Q_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_S_Q_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_S_Q_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_S_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_S_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_S_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_S_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_S_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_S_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_D_Q_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_D_Q_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_D_Q_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_D_Q_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_D_Q_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_D_Q_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_D_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_D_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_D_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_D_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_D_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_D_64Q   => fun _ => fct3_DYN
  | FEQ_Q_64Q          => fun _ => fct3_FEQ
  | FLT_Q_64Q          => fun _ => fct3_FLT
  | FLE_Q_64Q          => fun _ => fct3_FLE
  | FCLASS_Q_64Q       => fun _ => fct3_FCLASS
  | FCVT_RNE_W_Q_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_W_Q_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_W_Q_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_W_Q_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_W_Q_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_W_Q_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_WU_Q_64Q  => fun _ => fct3_RNE
  | FCVT_RTZ_WU_Q_64Q  => fun _ => fct3_RTZ
  | FCVT_RDN_WU_Q_64Q  => fun _ => fct3_RDN
  | FCVT_RUP_WU_Q_64Q  => fun _ => fct3_RUP
  | FCVT_RMM_WU_Q_64Q  => fun _ => fct3_RMM
  | FCVT_DYN_WU_Q_64Q  => fun _ => fct3_DYN
  | FCVT_RNE_Q_W_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_W_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_W_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_W_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_W_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_W_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_WU_64Q  => fun _ => fct3_RNE
  | FCVT_RTZ_Q_WU_64Q  => fun _ => fct3_RTZ
  | FCVT_RDN_Q_WU_64Q  => fun _ => fct3_RDN
  | FCVT_RUP_Q_WU_64Q  => fun _ => fct3_RUP
  | FCVT_RMM_Q_WU_64Q  => fun _ => fct3_RMM
  | FCVT_DYN_Q_WU_64Q  => fun _ => fct3_DYN
  | FCVT_RNE_L_Q_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_L_Q_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_L_Q_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_L_Q_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_L_Q_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_L_Q_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_LU_Q_64Q  => fun _ => fct3_RNE
  | FCVT_RTZ_LU_Q_64Q  => fun _ => fct3_RTZ
  | FCVT_RDN_LU_Q_64Q  => fun _ => fct3_RDN
  | FCVT_RUP_LU_Q_64Q  => fun _ => fct3_RUP
  | FCVT_RMM_LU_Q_64Q  => fun _ => fct3_RMM
  | FCVT_DYN_LU_Q_64Q  => fun _ => fct3_DYN
  | FCVT_RNE_Q_L_64Q   => fun _ => fct3_RNE
  | FCVT_RTZ_Q_L_64Q   => fun _ => fct3_RTZ
  | FCVT_RDN_Q_L_64Q   => fun _ => fct3_RDN
  | FCVT_RUP_Q_L_64Q   => fun _ => fct3_RUP
  | FCVT_RMM_Q_L_64Q   => fun _ => fct3_RMM
  | FCVT_DYN_Q_L_64Q   => fun _ => fct3_DYN
  | FCVT_RNE_Q_LU_64Q  => fun _ => fct3_RNE
  | FCVT_RTZ_Q_LU_64Q  => fun _ => fct3_RTZ
  | FCVT_RDN_Q_LU_64Q  => fun _ => fct3_RDN
  | FCVT_RUP_Q_LU_64Q  => fun _ => fct3_RUP
  | FCVT_RMM_Q_LU_64Q  => fun _ => fct3_RMM
  | FCVT_DYN_Q_LU_64Q  => fun _ => fct3_DYN
  | _                  => fun _ => False_rec _ _
  end); try reflexivity; simpl in e; inversion e.
Defined.
