Require Import Koika.Frontend.
Require Import rv.Instructions rv.IFields rv.ITypes.

Inductive opcode_name :=
| opc_OP     | opc_JALR   | opc_LOAD      | opc_OP_IMM | opc_MISC_MEM
| opc_STORE  | opc_BRANCH | opc_LUI       | opc_AUIPC  | opc_JAL
| opc_SYSTEM | opc_OP_32  | opc_OP_IMM_32 | opc_AMO    | opc_OP_FP
| opc_MADD   | opc_MSUB   | opc_NMSUB     | opc_NMADD  | opc_LOAD_FP
| opc_STORE_FP.

Scheme Equality for opcode_name.

Definition opcode_bin (o : opcode_name) :=
  match o with
  | opc_OP        => Ob~0~1~1~0~0~1~1 | opc_JALR    => Ob~1~1~0~0~1~1~1
  | opc_LOAD      => Ob~0~0~0~0~0~1~1 | opc_OP_IMM  => Ob~0~0~1~0~0~1~1
  | opc_MISC_MEM  => Ob~0~0~0~1~1~1~1 | opc_STORE   => Ob~0~1~0~0~0~1~1
  | opc_BRANCH    => Ob~1~1~0~0~0~1~1 | opc_LUI     => Ob~0~1~1~0~1~1~1
  | opc_AUIPC     => Ob~0~0~1~0~1~1~1 | opc_JAL     => Ob~1~1~0~1~1~1~1
  | opc_SYSTEM    => Ob~1~1~1~0~0~1~1 | opc_OP_32   => Ob~0~1~1~1~0~1~1
  | opc_OP_IMM_32 => Ob~0~0~1~1~0~1~1 | opc_AMO     => Ob~0~1~0~1~1~1~1
  | opc_OP_FP     => Ob~1~0~1~0~0~1~1 | opc_MADD    => Ob~1~0~0~0~0~1~1
  | opc_MSUB      => Ob~1~0~0~0~1~1~1 | opc_NMSUB   => Ob~1~0~0~1~0~1~1
  | opc_NMADD     => Ob~1~0~0~1~1~1~1 | opc_LOAD_FP => Ob~0~0~0~0~1~1~1
  | opc_STORE_FP  => Ob~0~1~0~0~1~1~1
  end.

Definition instruction_opcode (i : instruction) :=
  match i with
  | LUI_32I            => opc_LUI       | AUIPC_32I          => opc_AUIPC
  | JAL_32I            => opc_JAL       | JALR_32I           => opc_JALR
  | BEQ_32I            => opc_BRANCH    | BNE_32I            => opc_BRANCH
  | BLT_32I            => opc_BRANCH    | BGE_32I            => opc_BRANCH
  | BLTU_32I           => opc_BRANCH    | BGEU_32I           => opc_BRANCH
  | LB_32I             => opc_LOAD      | LH_32I             => opc_LOAD
  | LW_32I             => opc_LOAD      | LBU_32I            => opc_LOAD
  | LHU_32I            => opc_LOAD      | SB_32I             => opc_STORE
  | SH_32I             => opc_STORE     | SW_32I             => opc_STORE
  | ADDI_32I           => opc_OP_IMM    | SLTI_32I           => opc_OP_IMM
  | SLTIU_32I          => opc_OP_IMM    | XORI_32I           => opc_OP_IMM
  | ORI_32I            => opc_OP_IMM    | ANDI_32I           => opc_OP_IMM
  | SLLI_32I           => opc_OP_IMM    | SRLI_32I           => opc_OP_IMM
  | SRAI_32I           => opc_OP_IMM    | ADD_32I            => opc_OP
  | SUB_32I            => opc_OP        | SLL_32I            => opc_OP
  | SLT_32I            => opc_OP        | SLTU_32I           => opc_OP
  | XOR_32I            => opc_OP        | SRL_32I            => opc_OP
  | SRA_32I            => opc_OP        | OR_32I             => opc_OP
  | AND_32I            => opc_OP        | FENCE_32I          => opc_MISC_MEM
  | ECALL_32I          => opc_SYSTEM    | EBREAK_32I         => opc_SYSTEM
  | LUI_64I            => opc_LUI       | AUIPC_64I          => opc_AUIPC
  | JAL_64I            => opc_JAL       | JALR_64I           => opc_JALR
  | BEQ_64I            => opc_BRANCH    | BNE_64I            => opc_BRANCH
  | BLT_64I            => opc_BRANCH    | BGE_64I            => opc_BRANCH
  | BLTU_64I           => opc_BRANCH    | BGEU_64I           => opc_BRANCH
  | LB_64I             => opc_LOAD      | LH_64I             => opc_LOAD
  | LW_64I             => opc_LOAD      | LBU_64I            => opc_LOAD
  | LHU_64I            => opc_LOAD      | SB_64I             => opc_STORE
  | SH_64I             => opc_STORE     | SW_64I             => opc_STORE
  | ADDI_64I           => opc_OP_IMM    | SLTI_64I           => opc_OP_IMM
  | SLTIU_64I          => opc_OP_IMM    | XORI_64I           => opc_OP_IMM
  | ORI_64I            => opc_OP_IMM    | ANDI_64I           => opc_OP_IMM
  | SLLI_64I           => opc_OP_IMM    | SRLI_64I           => opc_OP_IMM
  | SRAI_64I           => opc_OP_IMM    | ADD_64I            => opc_OP
  | SUB_64I            => opc_OP        | SLL_64I            => opc_OP
  | SLT_64I            => opc_OP        | SLTU_64I           => opc_OP
  | XOR_64I            => opc_OP        | SRL_64I            => opc_OP
  | SRA_64I            => opc_OP        | OR_64I             => opc_OP
  | AND_64I            => opc_OP        | FENCE_64I          => opc_MISC_MEM
  | ECALL_64I          => opc_SYSTEM    | EBREAK_64I         => opc_SYSTEM
  | LWU_64I            => opc_LOAD      | LD_64I             => opc_LOAD
  | SD_64I             => opc_STORE     | ADDIW_64I          => opc_OP_IMM_32
  | SLLIW_64I          => opc_OP_IMM_32 | SRLIW_64I          => opc_OP_IMM_32
  | SRAIW_64I          => opc_OP_IMM_32 | ADDW_64I           => opc_OP_32
  | SUBW_64I           => opc_OP_32     | SLLW_64I           => opc_OP_32
  | SRLW_64I           => opc_OP_32     | SRAW_64I           => opc_OP_32
  | FENCE_I_32Zifencei => opc_MISC_MEM  | FENCE_I_64Zifencei => opc_MISC_MEM
  | CSRRW_32Zicsr      => opc_SYSTEM    | CSRRS_32Zicsr      => opc_SYSTEM
  | CSRRC_32Zicsr      => opc_SYSTEM    | CSRRWI_32Zicsr     => opc_SYSTEM
  | CSRRSI_32Zicsr     => opc_SYSTEM    | CSRRCI_32Zicsr     => opc_SYSTEM
  | CSRRW_64Zicsr      => opc_SYSTEM    | CSRRS_64Zicsr      => opc_SYSTEM
  | CSRRC_64Zicsr      => opc_SYSTEM    | CSRRWI_64Zicsr     => opc_SYSTEM
  | CSRRSI_64Zicsr     => opc_SYSTEM    | CSRRCI_64Zicsr     => opc_SYSTEM
  | MUL_32M            => opc_OP        | MULH_32M           => opc_OP
  | MULHSU_32M         => opc_OP        | MULHU_32M          => opc_OP
  | DIV_32M            => opc_OP        | DIVU_32M           => opc_OP
  | REM_32M            => opc_OP        | REMU_32M           => opc_OP
  | MUL_64M            => opc_OP        | MULH_64M           => opc_OP
  | MULHSU_64M         => opc_OP        | MULHU_64M          => opc_OP
  | DIV_64M            => opc_OP        | DIVU_64M           => opc_OP
  | REM_64M            => opc_OP        | REMU_64M           => opc_OP
  | MULW_64M           => opc_OP_32     | DIVW_64M           => opc_OP_32
  | DIVUW_64M          => opc_OP_32     | REMW_64M           => opc_OP_32
  | REMUW_64M          => opc_OP_32     | LR_W_00_32A        => opc_AMO
  | LR_W_01_32A        => opc_AMO       | LR_W_10_32A        => opc_AMO
  | LR_W_11_32A        => opc_AMO       | SC_W_00_32A        => opc_AMO
  | SC_W_01_32A        => opc_AMO       | SC_W_10_32A        => opc_AMO
  | SC_W_11_32A        => opc_AMO       | AMOSWAP_W_00_32A   => opc_AMO
  | AMOSWAP_W_01_32A   => opc_AMO       | AMOSWAP_W_10_32A   => opc_AMO
  | AMOSWAP_W_11_32A   => opc_AMO       | AMOADD_W_00_32A    => opc_AMO
  | AMOADD_W_01_32A    => opc_AMO       | AMOADD_W_10_32A    => opc_AMO
  | AMOADD_W_11_32A    => opc_AMO       | AMOXOR_W_00_32A    => opc_AMO
  | AMOXOR_W_01_32A    => opc_AMO       | AMOXOR_W_10_32A    => opc_AMO
  | AMOXOR_W_11_32A    => opc_AMO       | AMOAND_W_00_32A    => opc_AMO
  | AMOAND_W_01_32A    => opc_AMO       | AMOAND_W_10_32A    => opc_AMO
  | AMOAND_W_11_32A    => opc_AMO       | AMOOR_W_00_32A     => opc_AMO
  | AMOOR_W_01_32A     => opc_AMO       | AMOOR_W_10_32A     => opc_AMO
  | AMOOR_W_11_32A     => opc_AMO       | AMOMIN_W_00_32A    => opc_AMO
  | AMOMIN_W_01_32A    => opc_AMO       | AMOMIN_W_10_32A    => opc_AMO
  | AMOMIN_W_11_32A    => opc_AMO       | AMOMAX_W_00_32A    => opc_AMO
  | AMOMAX_W_01_32A    => opc_AMO       | AMOMAX_W_10_32A    => opc_AMO
  | AMOMAX_W_11_32A    => opc_AMO       | AMOMINU_W_00_32A   => opc_AMO
  | AMOMINU_W_01_32A   => opc_AMO       | AMOMINU_W_10_32A   => opc_AMO
  | AMOMINU_W_11_32A   => opc_AMO       | AMOMAXU_W_00_32A   => opc_AMO
  | AMOMAXU_W_01_32A   => opc_AMO       | AMOMAXU_W_10_32A   => opc_AMO
  | AMOMAXU_W_11_32A   => opc_AMO       | LR_W_00_64A        => opc_AMO
  | LR_W_01_64A        => opc_AMO       | LR_W_10_64A        => opc_AMO
  | LR_W_11_64A        => opc_AMO       | SC_W_00_64A        => opc_AMO
  | SC_W_01_64A        => opc_AMO       | SC_W_10_64A        => opc_AMO
  | SC_W_11_64A        => opc_AMO       | AMOSWAP_W_00_64A   => opc_AMO
  | AMOSWAP_W_01_64A   => opc_AMO       | AMOSWAP_W_10_64A   => opc_AMO
  | AMOSWAP_W_11_64A   => opc_AMO       | AMOADD_W_00_64A    => opc_AMO
  | AMOADD_W_01_64A    => opc_AMO       | AMOADD_W_10_64A    => opc_AMO
  | AMOADD_W_11_64A    => opc_AMO       | AMOXOR_W_00_64A    => opc_AMO
  | AMOXOR_W_01_64A    => opc_AMO       | AMOXOR_W_10_64A    => opc_AMO
  | AMOXOR_W_11_64A    => opc_AMO       | AMOAND_W_00_64A    => opc_AMO
  | AMOAND_W_01_64A    => opc_AMO       | AMOAND_W_10_64A    => opc_AMO
  | AMOAND_W_11_64A    => opc_AMO       | AMOOR_W_00_64A     => opc_AMO
  | AMOOR_W_01_64A     => opc_AMO       | AMOOR_W_10_64A     => opc_AMO
  | AMOOR_W_11_64A     => opc_AMO       | AMOMIN_W_00_64A    => opc_AMO
  | AMOMIN_W_01_64A    => opc_AMO       | AMOMIN_W_10_64A    => opc_AMO
  | AMOMIN_W_11_64A    => opc_AMO       | AMOMAX_W_00_64A    => opc_AMO
  | AMOMAX_W_01_64A    => opc_AMO       | AMOMAX_W_10_64A    => opc_AMO
  | AMOMAX_W_11_64A    => opc_AMO       | AMOMINU_W_00_64A   => opc_AMO
  | AMOMINU_W_01_64A   => opc_AMO       | AMOMINU_W_10_64A   => opc_AMO
  | AMOMINU_W_11_64A   => opc_AMO       | AMOMAXU_W_00_64A   => opc_AMO
  | AMOMAXU_W_01_64A   => opc_AMO       | AMOMAXU_W_10_64A   => opc_AMO
  | AMOMAXU_W_11_64A   => opc_AMO       | LR_D_00_64A        => opc_AMO
  | LR_D_01_64A        => opc_AMO       | LR_D_10_64A        => opc_AMO
  | LR_D_11_64A        => opc_AMO       | SC_D_00_64A        => opc_AMO
  | SC_D_01_64A        => opc_AMO       | SC_D_10_64A        => opc_AMO
  | SC_D_11_64A        => opc_AMO       | AMOSWAP_D_00_64A   => opc_AMO
  | AMOSWAP_D_01_64A   => opc_AMO       | AMOSWAP_D_10_64A   => opc_AMO
  | AMOSWAP_D_11_64A   => opc_AMO       | AMOADD_D_00_64A    => opc_AMO
  | AMOADD_D_01_64A    => opc_AMO       | AMOADD_D_10_64A    => opc_AMO
  | AMOADD_D_11_64A    => opc_AMO       | AMOXOR_D_00_64A    => opc_AMO
  | AMOXOR_D_01_64A    => opc_AMO       | AMOXOR_D_10_64A    => opc_AMO
  | AMOXOR_D_11_64A    => opc_AMO       | AMOAND_D_00_64A    => opc_AMO
  | AMOAND_D_01_64A    => opc_AMO       | AMOAND_D_10_64A    => opc_AMO
  | AMOAND_D_11_64A    => opc_AMO       | AMOOR_D_00_64A     => opc_AMO
  | AMOOR_D_01_64A     => opc_AMO       | AMOOR_D_10_64A     => opc_AMO
  | AMOOR_D_11_64A     => opc_AMO       | AMOMIN_D_00_64A    => opc_AMO
  | AMOMIN_D_01_64A    => opc_AMO       | AMOMIN_D_10_64A    => opc_AMO
  | AMOMIN_D_11_64A    => opc_AMO       | AMOMAX_D_00_64A    => opc_AMO
  | AMOMAX_D_01_64A    => opc_AMO       | AMOMAX_D_10_64A    => opc_AMO
  | AMOMAX_D_11_64A    => opc_AMO       | AMOMINU_D_00_64A   => opc_AMO
  | AMOMINU_D_01_64A   => opc_AMO       | AMOMINU_D_10_64A   => opc_AMO
  | AMOMINU_D_11_64A   => opc_AMO       | AMOMAXU_D_00_64A   => opc_AMO
  | AMOMAXU_D_01_64A   => opc_AMO       | AMOMAXU_D_10_64A   => opc_AMO
  | AMOMAXU_D_11_64A   => opc_AMO       | FLW_32F            => opc_LOAD_FP
  | FSW_32F            => opc_STORE_FP  | FMADD_RNE_S_32F    => opc_MADD
  | FMADD_RTZ_S_32F    => opc_MADD      | FMADD_RDN_S_32F    => opc_MADD
  | FMADD_RUP_S_32F    => opc_MADD      | FMADD_RMM_S_32F    => opc_MADD
  | FMADD_DYN_S_32F    => opc_MADD      | FMSUB_RNE_S_32F    => opc_MSUB
  | FMSUB_RTZ_S_32F    => opc_MSUB      | FMSUB_RDN_S_32F    => opc_MSUB
  | FMSUB_RUP_S_32F    => opc_MSUB      | FMSUB_RMM_S_32F    => opc_MSUB
  | FMSUB_DYN_S_32F    => opc_MSUB      | FNMSUB_RNE_S_32F   => opc_NMSUB
  | FNMSUB_RTZ_S_32F   => opc_NMSUB     | FNMSUB_RDN_S_32F   => opc_NMSUB
  | FNMSUB_RUP_S_32F   => opc_NMSUB     | FNMSUB_RMM_S_32F   => opc_NMSUB
  | FNMSUB_DYN_S_32F   => opc_NMSUB     | FNMADD_RNE_S_32F   => opc_NMADD
  | FNMADD_RTZ_S_32F   => opc_NMADD     | FNMADD_RDN_S_32F   => opc_NMADD
  | FNMADD_RUP_S_32F   => opc_NMADD     | FNMADD_RMM_S_32F   => opc_NMADD
  | FNMADD_DYN_S_32F   => opc_NMADD     | FADD_RNE_S_32F     => opc_OP_FP
  | FADD_RTZ_S_32F     => opc_OP_FP     | FADD_RDN_S_32F     => opc_OP_FP
  | FADD_RUP_S_32F     => opc_OP_FP     | FADD_RMM_S_32F     => opc_OP_FP
  | FADD_DYN_S_32F     => opc_OP_FP     | FSUB_RNE_S_32F     => opc_OP_FP
  | FSUB_RTZ_S_32F     => opc_OP_FP     | FSUB_RDN_S_32F     => opc_OP_FP
  | FSUB_RUP_S_32F     => opc_OP_FP     | FSUB_RMM_S_32F     => opc_OP_FP
  | FSUB_DYN_S_32F     => opc_OP_FP     | FMUL_RNE_S_32F     => opc_OP_FP
  | FMUL_RTZ_S_32F     => opc_OP_FP     | FMUL_RDN_S_32F     => opc_OP_FP
  | FMUL_RUP_S_32F     => opc_OP_FP     | FMUL_RMM_S_32F     => opc_OP_FP
  | FMUL_DYN_S_32F     => opc_OP_FP     | FDIV_RNE_S_32F     => opc_OP_FP
  | FDIV_RTZ_S_32F     => opc_OP_FP     | FDIV_RDN_S_32F     => opc_OP_FP
  | FDIV_RUP_S_32F     => opc_OP_FP     | FDIV_RMM_S_32F     => opc_OP_FP
  | FDIV_DYN_S_32F     => opc_OP_FP     | FSQRT_RNE_S_32F    => opc_OP_FP
  | FSQRT_RTZ_S_32F    => opc_OP_FP     | FSQRT_RDN_S_32F    => opc_OP_FP
  | FSQRT_RUP_S_32F    => opc_OP_FP     | FSQRT_RMM_S_32F    => opc_OP_FP
  | FSQRT_DYN_S_32F    => opc_OP_FP     | FSGNJ_S_32F        => opc_OP_FP
  | FSGNJN_S_32F       => opc_OP_FP     | FSGNJX_S_32F       => opc_OP_FP
  | FMIN_S_32F         => opc_OP_FP     | FMAX_S_32F         => opc_OP_FP
  | FCVT_RNE_W_S_32F   => opc_OP_FP     | FCVT_RTZ_W_S_32F   => opc_OP_FP
  | FCVT_RDN_W_S_32F   => opc_OP_FP     | FCVT_RUP_W_S_32F   => opc_OP_FP
  | FCVT_RMM_W_S_32F   => opc_OP_FP     | FCVT_DYN_W_S_32F   => opc_OP_FP
  | FCVT_RNE_WU_S_32F  => opc_OP_FP     | FCVT_RTZ_WU_S_32F  => opc_OP_FP
  | FCVT_RDN_WU_S_32F  => opc_OP_FP     | FCVT_RUP_WU_S_32F  => opc_OP_FP
  | FCVT_RMM_WU_S_32F  => opc_OP_FP     | FCVT_DYN_WU_S_32F  => opc_OP_FP
  | FMV_X_W_32F        => opc_OP_FP     | FEQ_S_32F          => opc_OP_FP
  | FLT_S_32F          => opc_OP_FP     | FLE_S_32F          => opc_OP_FP
  | FCLASS_S_32F       => opc_OP_FP     | FCVT_RNE_S_W_32F   => opc_OP_FP
  | FCVT_RTZ_S_W_32F   => opc_OP_FP     | FCVT_RDN_S_W_32F   => opc_OP_FP
  | FCVT_RUP_S_W_32F   => opc_OP_FP     | FCVT_RMM_S_W_32F   => opc_OP_FP
  | FCVT_DYN_S_W_32F   => opc_OP_FP     | FCVT_RNE_S_WU_32F  => opc_OP_FP
  | FCVT_RTZ_S_WU_32F  => opc_OP_FP     | FCVT_RDN_S_WU_32F  => opc_OP_FP
  | FCVT_RUP_S_WU_32F  => opc_OP_FP     | FCVT_RMM_S_WU_32F  => opc_OP_FP
  | FCVT_DYN_S_WU_32F  => opc_OP_FP     | FMV_W_X_32F        => opc_OP_FP
  | FLW_64F            => opc_LOAD_FP   | FSW_64F            => opc_LOAD_FP
  | FMADD_RNE_S_64F    => opc_MADD      | FMADD_RTZ_S_64F    => opc_MADD
  | FMADD_RDN_S_64F    => opc_MADD      | FMADD_RUP_S_64F    => opc_MADD
  | FMADD_RMM_S_64F    => opc_MADD      | FMADD_DYN_S_64F    => opc_MADD
  | FMSUB_RNE_S_64F    => opc_MSUB      | FMSUB_RTZ_S_64F    => opc_MSUB
  | FMSUB_RDN_S_64F    => opc_MSUB      | FMSUB_RUP_S_64F    => opc_MSUB
  | FMSUB_RMM_S_64F    => opc_MSUB      | FMSUB_DYN_S_64F    => opc_MSUB
  | FNMSUB_RNE_S_64F   => opc_NMSUB     | FNMSUB_RTZ_S_64F   => opc_NMSUB
  | FNMSUB_RDN_S_64F   => opc_NMSUB     | FNMSUB_RUP_S_64F   => opc_NMSUB
  | FNMSUB_RMM_S_64F   => opc_NMSUB     | FNMSUB_DYN_S_64F   => opc_NMSUB
  | FNMADD_RNE_S_64F   => opc_NMADD     | FNMADD_RTZ_S_64F   => opc_NMADD
  | FNMADD_RDN_S_64F   => opc_NMADD     | FNMADD_RUP_S_64F   => opc_NMADD
  | FNMADD_RMM_S_64F   => opc_NMADD     | FNMADD_DYN_S_64F   => opc_NMADD
  | FADD_RNE_S_64F     => opc_OP_FP     | FADD_RTZ_S_64F     => opc_OP_FP
  | FADD_RDN_S_64F     => opc_OP_FP     | FADD_RUP_S_64F     => opc_OP_FP
  | FADD_RMM_S_64F     => opc_OP_FP     | FADD_DYN_S_64F     => opc_OP_FP
  | FSUB_RNE_S_64F     => opc_OP_FP     | FSUB_RTZ_S_64F     => opc_OP_FP
  | FSUB_RDN_S_64F     => opc_OP_FP     | FSUB_RUP_S_64F     => opc_OP_FP
  | FSUB_RMM_S_64F     => opc_OP_FP     | FSUB_DYN_S_64F     => opc_OP_FP
  | FMUL_RNE_S_64F     => opc_OP_FP     | FMUL_RTZ_S_64F     => opc_OP_FP
  | FMUL_RDN_S_64F     => opc_OP_FP     | FMUL_RUP_S_64F     => opc_OP_FP
  | FMUL_RMM_S_64F     => opc_OP_FP     | FMUL_DYN_S_64F     => opc_OP_FP
  | FDIV_RNE_S_64F     => opc_OP_FP     | FDIV_RTZ_S_64F     => opc_OP_FP
  | FDIV_RDN_S_64F     => opc_OP_FP     | FDIV_RUP_S_64F     => opc_OP_FP
  | FDIV_RMM_S_64F     => opc_OP_FP     | FDIV_DYN_S_64F     => opc_OP_FP
  | FSQRT_RNE_S_64F    => opc_OP_FP     | FSQRT_RTZ_S_64F    => opc_OP_FP
  | FSQRT_RDN_S_64F    => opc_OP_FP     | FSQRT_RUP_S_64F    => opc_OP_FP
  | FSQRT_RMM_S_64F    => opc_OP_FP     | FSQRT_DYN_S_64F    => opc_OP_FP
  | FSGNJ_S_64F        => opc_OP_FP     | FSGNJN_S_64F       => opc_OP_FP
  | FSGNJX_S_64F       => opc_OP_FP     | FMIN_S_64F         => opc_OP_FP
  | FMAX_S_64F         => opc_OP_FP     | FCVT_RNE_W_S_64F   => opc_OP_FP
  | FCVT_RTZ_W_S_64F   => opc_OP_FP     | FCVT_RDN_W_S_64F   => opc_OP_FP
  | FCVT_RUP_W_S_64F   => opc_OP_FP     | FCVT_RMM_W_S_64F   => opc_OP_FP
  | FCVT_DYN_W_S_64F   => opc_OP_FP     | FCVT_RNE_WU_S_64F  => opc_OP_FP
  | FCVT_RTZ_WU_S_64F  => opc_OP_FP     | FCVT_RDN_WU_S_64F  => opc_OP_FP
  | FCVT_RUP_WU_S_64F  => opc_OP_FP     | FCVT_RMM_WU_S_64F  => opc_OP_FP
  | FCVT_DYN_WU_S_64F  => opc_OP_FP     | FMV_X_W_64F        => opc_OP_FP
  | FEQ_S_64F          => opc_OP_FP     | FLT_S_64F          => opc_OP_FP
  | FLE_S_64F          => opc_OP_FP     | FCLASS_S_64F       => opc_OP_FP
  | FCVT_RNE_S_W_64F   => opc_OP_FP     | FCVT_RTZ_S_W_64F   => opc_OP_FP
  | FCVT_RDN_S_W_64F   => opc_OP_FP     | FCVT_RUP_S_W_64F   => opc_OP_FP
  | FCVT_RMM_S_W_64F   => opc_OP_FP     | FCVT_DYN_S_W_64F   => opc_OP_FP
  | FCVT_RNE_S_WU_64F  => opc_OP_FP     | FCVT_RTZ_S_WU_64F  => opc_OP_FP
  | FCVT_RDN_S_WU_64F  => opc_OP_FP     | FCVT_RUP_S_WU_64F  => opc_OP_FP
  | FCVT_RMM_S_WU_64F  => opc_OP_FP     | FCVT_DYN_S_WU_64F  => opc_OP_FP
  | FMV_W_X_64F        => opc_OP_FP     | FCVT_RNE_L_S_64F   => opc_OP_FP
  | FCVT_RTZ_L_S_64F   => opc_OP_FP     | FCVT_RDN_L_S_64F   => opc_OP_FP
  | FCVT_RUP_L_S_64F   => opc_OP_FP     | FCVT_RMM_L_S_64F   => opc_OP_FP
  | FCVT_DYN_L_S_64F   => opc_OP_FP     | FCVT_RNE_LU_S_64F  => opc_OP_FP
  | FCVT_RTZ_LU_S_64F  => opc_OP_FP     | FCVT_RDN_LU_S_64F  => opc_OP_FP
  | FCVT_RUP_LU_S_64F  => opc_OP_FP     | FCVT_RMM_LU_S_64F  => opc_OP_FP
  | FCVT_DYN_LU_S_64F  => opc_OP_FP     | FCVT_RNE_S_L_64F   => opc_OP_FP
  | FCVT_RTZ_S_L_64F   => opc_OP_FP     | FCVT_RDN_S_L_64F   => opc_OP_FP
  | FCVT_RUP_S_L_64F   => opc_OP_FP     | FCVT_RMM_S_L_64F   => opc_OP_FP
  | FCVT_DYN_S_L_64F   => opc_OP_FP     | FCVT_RNE_S_LU_64F  => opc_OP_FP
  | FCVT_RTZ_S_LU_64F  => opc_OP_FP     | FCVT_RDN_S_LU_64F  => opc_OP_FP
  | FCVT_RUP_S_LU_64F  => opc_OP_FP     | FCVT_RMM_S_LU_64F  => opc_OP_FP
  | FCVT_DYN_S_LU_64F  => opc_OP_FP     | FLD_32D            => opc_LOAD_FP
  | FSD_32D            => opc_STORE_FP  | FMADD_RNE_D_32D    => opc_MADD
  | FMADD_RTZ_D_32D    => opc_MADD      | FMADD_RDN_D_32D    => opc_MADD
  | FMADD_RUP_D_32D    => opc_MADD      | FMADD_RMM_D_32D    => opc_MADD
  | FMADD_DYN_D_32D    => opc_MADD      | FMSUB_RNE_D_32D    => opc_MSUB
  | FMSUB_RTZ_D_32D    => opc_MSUB      | FMSUB_RDN_D_32D    => opc_MSUB
  | FMSUB_RUP_D_32D    => opc_MSUB      | FMSUB_RMM_D_32D    => opc_MSUB
  | FMSUB_DYN_D_32D    => opc_MSUB      | FNMSUB_RNE_D_32D   => opc_NMSUB
  | FNMSUB_RTZ_D_32D   => opc_NMSUB     | FNMSUB_RDN_D_32D   => opc_NMSUB
  | FNMSUB_RUP_D_32D   => opc_NMSUB     | FNMSUB_RMM_D_32D   => opc_NMSUB
  | FNMSUB_DYN_D_32D   => opc_NMSUB     | FNMADD_RNE_D_32D   => opc_NMADD
  | FNMADD_RTZ_D_32D   => opc_NMADD     | FNMADD_RDN_D_32D   => opc_NMADD
  | FNMADD_RUP_D_32D   => opc_NMADD     | FNMADD_RMM_D_32D   => opc_NMADD
  | FNMADD_DYN_D_32D   => opc_NMADD     | FADD_RNE_D_32D     => opc_OP_FP
  | FADD_RTZ_D_32D     => opc_OP_FP     | FADD_RDN_D_32D     => opc_OP_FP
  | FADD_RUP_D_32D     => opc_OP_FP     | FADD_RMM_D_32D     => opc_OP_FP
  | FADD_DYN_D_32D     => opc_OP_FP     | FSUB_RNE_D_32D     => opc_OP_FP
  | FSUB_RTZ_D_32D     => opc_OP_FP     | FSUB_RDN_D_32D     => opc_OP_FP
  | FSUB_RUP_D_32D     => opc_OP_FP     | FSUB_RMM_D_32D     => opc_OP_FP
  | FSUB_DYN_D_32D     => opc_OP_FP     | FMUL_RNE_D_32D     => opc_OP_FP
  | FMUL_RTZ_D_32D     => opc_OP_FP     | FMUL_RDN_D_32D     => opc_OP_FP
  | FMUL_RUP_D_32D     => opc_OP_FP     | FMUL_RMM_D_32D     => opc_OP_FP
  | FMUL_DYN_D_32D     => opc_OP_FP     | FDIV_RNE_D_32D     => opc_OP_FP
  | FDIV_RTZ_D_32D     => opc_OP_FP     | FDIV_RDN_D_32D     => opc_OP_FP
  | FDIV_RUP_D_32D     => opc_OP_FP     | FDIV_RMM_D_32D     => opc_OP_FP
  | FDIV_DYN_D_32D     => opc_OP_FP     | FSQRT_RNE_D_32D    => opc_OP_FP
  | FSQRT_RTZ_D_32D    => opc_OP_FP     | FSQRT_RDN_D_32D    => opc_OP_FP
  | FSQRT_RUP_D_32D    => opc_OP_FP     | FSQRT_RMM_D_32D    => opc_OP_FP
  | FSQRT_DYN_D_32D    => opc_OP_FP     | FSGNJ_D_32D        => opc_OP_FP
  | FSGNJN_D_32D       => opc_OP_FP     | FSGNJX_D_32D       => opc_OP_FP
  | FMIN_D_32D         => opc_OP_FP     | FMAX_D_32D         => opc_OP_FP
  | FCVT_RNE_S_D_32D   => opc_OP_FP     | FCVT_RTZ_S_D_32D   => opc_OP_FP
  | FCVT_RDN_S_D_32D   => opc_OP_FP     | FCVT_RUP_S_D_32D   => opc_OP_FP
  | FCVT_RMM_S_D_32D   => opc_OP_FP     | FCVT_DYN_S_D_32D   => opc_OP_FP
  | FCVT_RNE_D_S_32D   => opc_OP_FP     | FCVT_RTZ_D_S_32D   => opc_OP_FP
  | FCVT_RDN_D_S_32D   => opc_OP_FP     | FCVT_RUP_D_S_32D   => opc_OP_FP
  | FCVT_RMM_D_S_32D   => opc_OP_FP     | FCVT_DYN_D_S_32D   => opc_OP_FP
  | FEQ_D_32D          => opc_OP_FP     | FLT_D_32D          => opc_OP_FP
  | FLE_D_32D          => opc_OP_FP     | FCLASS_D_32D       => opc_OP_FP
  | FCVT_RNE_W_D_32D   => opc_OP_FP     | FCVT_RTZ_W_D_32D   => opc_OP_FP
  | FCVT_RDN_W_D_32D   => opc_OP_FP     | FCVT_RUP_W_D_32D   => opc_OP_FP
  | FCVT_RMM_W_D_32D   => opc_OP_FP     | FCVT_DYN_W_D_32D   => opc_OP_FP
  | FCVT_RNE_WU_D_32D  => opc_OP_FP     | FCVT_RTZ_WU_D_32D  => opc_OP_FP
  | FCVT_RDN_WU_D_32D  => opc_OP_FP     | FCVT_RUP_WU_D_32D  => opc_OP_FP
  | FCVT_RMM_WU_D_32D  => opc_OP_FP     | FCVT_DYN_WU_D_32D  => opc_OP_FP
  | FCVT_RNE_D_W_32D   => opc_OP_FP     | FCVT_RTZ_D_W_32D   => opc_OP_FP
  | FCVT_RDN_D_W_32D   => opc_OP_FP     | FCVT_RUP_D_W_32D   => opc_OP_FP
  | FCVT_RMM_D_W_32D   => opc_OP_FP     | FCVT_DYN_D_W_32D   => opc_OP_FP
  | FCVT_RNE_D_WU_32D  => opc_OP_FP     | FCVT_RTZ_D_WU_32D  => opc_OP_FP
  | FCVT_RDN_D_WU_32D  => opc_OP_FP     | FCVT_RUP_D_WU_32D  => opc_OP_FP
  | FCVT_RMM_D_WU_32D  => opc_OP_FP     | FCVT_DYN_D_WU_32D  => opc_OP_FP
  | FLD_64D            => opc_LOAD_FP   | FSD_64D            => opc_STORE_FP
  | FMADD_RNE_D_64D    => opc_MADD      | FMADD_RTZ_D_64D    => opc_MADD
  | FMADD_RDN_D_64D    => opc_MADD      | FMADD_RUP_D_64D    => opc_MADD
  | FMADD_RMM_D_64D    => opc_MADD      | FMADD_DYN_D_64D    => opc_MADD
  | FMSUB_RNE_D_64D    => opc_MSUB      | FMSUB_RTZ_D_64D    => opc_MSUB
  | FMSUB_RDN_D_64D    => opc_MSUB      | FMSUB_RUP_D_64D    => opc_MSUB
  | FMSUB_RMM_D_64D    => opc_MSUB      | FMSUB_DYN_D_64D    => opc_MSUB
  | FNMSUB_RNE_D_64D   => opc_NMSUB     | FNMSUB_RTZ_D_64D   => opc_NMSUB
  | FNMSUB_RDN_D_64D   => opc_NMSUB     | FNMSUB_RUP_D_64D   => opc_NMSUB
  | FNMSUB_RMM_D_64D   => opc_NMSUB     | FNMSUB_DYN_D_64D   => opc_NMSUB
  | FNMADD_RNE_D_64D   => opc_NMADD     | FNMADD_RTZ_D_64D   => opc_NMADD
  | FNMADD_RDN_D_64D   => opc_NMADD     | FNMADD_RUP_D_64D   => opc_NMADD
  | FNMADD_RMM_D_64D   => opc_NMADD     | FNMADD_DYN_D_64D   => opc_NMADD
  | FADD_RNE_D_64D     => opc_OP_FP     | FADD_RTZ_D_64D     => opc_OP_FP
  | FADD_RDN_D_64D     => opc_OP_FP     | FADD_RUP_D_64D     => opc_OP_FP
  | FADD_RMM_D_64D     => opc_OP_FP     | FADD_DYN_D_64D     => opc_OP_FP
  | FSUB_RNE_D_64D     => opc_OP_FP     | FSUB_RTZ_D_64D     => opc_OP_FP
  | FSUB_RDN_D_64D     => opc_OP_FP     | FSUB_RUP_D_64D     => opc_OP_FP
  | FSUB_RMM_D_64D     => opc_OP_FP     | FSUB_DYN_D_64D     => opc_OP_FP
  | FMUL_RNE_D_64D     => opc_OP_FP     | FMUL_RTZ_D_64D     => opc_OP_FP
  | FMUL_RDN_D_64D     => opc_OP_FP     | FMUL_RUP_D_64D     => opc_OP_FP
  | FMUL_RMM_D_64D     => opc_OP_FP     | FMUL_DYN_D_64D     => opc_OP_FP
  | FDIV_RNE_D_64D     => opc_OP_FP     | FDIV_RTZ_D_64D     => opc_OP_FP
  | FDIV_RDN_D_64D     => opc_OP_FP     | FDIV_RUP_D_64D     => opc_OP_FP
  | FDIV_RMM_D_64D     => opc_OP_FP     | FDIV_DYN_D_64D     => opc_OP_FP
  | FSQRT_RNE_D_64D    => opc_OP_FP     | FSQRT_RTZ_D_64D    => opc_OP_FP
  | FSQRT_RDN_D_64D    => opc_OP_FP     | FSQRT_RUP_D_64D    => opc_OP_FP
  | FSQRT_RMM_D_64D    => opc_OP_FP     | FSQRT_DYN_D_64D    => opc_OP_FP
  | FSGNJ_D_64D        => opc_OP_FP     | FSGNJN_D_64D       => opc_OP_FP
  | FSGNJX_D_64D       => opc_OP_FP     | FMIN_D_64D         => opc_OP_FP
  | FMAX_D_64D         => opc_OP_FP     | FCVT_RNE_S_D_64D   => opc_OP_FP
  | FCVT_RTZ_S_D_64D   => opc_OP_FP     | FCVT_RDN_S_D_64D   => opc_OP_FP
  | FCVT_RUP_S_D_64D   => opc_OP_FP     | FCVT_RMM_S_D_64D   => opc_OP_FP
  | FCVT_DYN_S_D_64D   => opc_OP_FP     | FCVT_RNE_D_S_64D   => opc_OP_FP
  | FCVT_RTZ_D_S_64D   => opc_OP_FP     | FCVT_RDN_D_S_64D   => opc_OP_FP
  | FCVT_RUP_D_S_64D   => opc_OP_FP     | FCVT_RMM_D_S_64D   => opc_OP_FP
  | FCVT_DYN_D_S_64D   => opc_OP_FP     | FEQ_D_64D          => opc_OP_FP
  | FLT_D_64D          => opc_OP_FP     | FLE_D_64D          => opc_OP_FP
  | FCLASS_D_64D       => opc_OP_FP     | FCVT_RNE_W_D_64D   => opc_OP_FP
  | FCVT_RTZ_W_D_64D   => opc_OP_FP     | FCVT_RDN_W_D_64D   => opc_OP_FP
  | FCVT_RUP_W_D_64D   => opc_OP_FP     | FCVT_RMM_W_D_64D   => opc_OP_FP
  | FCVT_DYN_W_D_64D   => opc_OP_FP     | FCVT_RNE_WU_D_64D  => opc_OP_FP
  | FCVT_RTZ_WU_D_64D  => opc_OP_FP     | FCVT_RDN_WU_D_64D  => opc_OP_FP
  | FCVT_RUP_WU_D_64D  => opc_OP_FP     | FCVT_RMM_WU_D_64D  => opc_OP_FP
  | FCVT_DYN_WU_D_64D  => opc_OP_FP     | FCVT_RNE_D_W_64D   => opc_OP_FP
  | FCVT_RTZ_D_W_64D   => opc_OP_FP     | FCVT_RDN_D_W_64D   => opc_OP_FP
  | FCVT_RUP_D_W_64D   => opc_OP_FP     | FCVT_RMM_D_W_64D   => opc_OP_FP
  | FCVT_DYN_D_W_64D   => opc_OP_FP     | FCVT_RNE_D_WU_64D  => opc_OP_FP
  | FCVT_RTZ_D_WU_64D  => opc_OP_FP     | FCVT_RDN_D_WU_64D  => opc_OP_FP
  | FCVT_RUP_D_WU_64D  => opc_OP_FP     | FCVT_RMM_D_WU_64D  => opc_OP_FP
  | FCVT_DYN_D_WU_64D  => opc_OP_FP     | FCVT_RNE_L_D_64D   => opc_OP_FP
  | FCVT_RTZ_L_D_64D   => opc_OP_FP     | FCVT_RDN_L_D_64D   => opc_OP_FP
  | FCVT_RUP_L_D_64D   => opc_OP_FP     | FCVT_RMM_L_D_64D   => opc_OP_FP
  | FCVT_DYN_L_D_64D   => opc_OP_FP     | FCVT_RNE_LU_D_64D  => opc_OP_FP
  | FCVT_RTZ_LU_D_64D  => opc_OP_FP     | FCVT_RDN_LU_D_64D  => opc_OP_FP
  | FCVT_RUP_LU_D_64D  => opc_OP_FP     | FCVT_RMM_LU_D_64D  => opc_OP_FP
  | FCVT_DYN_LU_D_64D  => opc_OP_FP     | FMV_X_D_64D        => opc_OP_FP
  | FCVT_RNE_D_L_64D   => opc_OP_FP     | FCVT_RTZ_D_L_64D   => opc_OP_FP
  | FCVT_RDN_D_L_64D   => opc_OP_FP     | FCVT_RUP_D_L_64D   => opc_OP_FP
  | FCVT_RMM_D_L_64D   => opc_OP_FP     | FCVT_DYN_D_L_64D   => opc_OP_FP
  | FCVT_RNE_D_LU_64D  => opc_OP_FP     | FCVT_RTZ_D_LU_64D  => opc_OP_FP
  | FCVT_RDN_D_LU_64D  => opc_OP_FP     | FCVT_RUP_D_LU_64D  => opc_OP_FP
  | FCVT_RMM_D_LU_64D  => opc_OP_FP     | FCVT_DYN_D_LU_64D  => opc_OP_FP
  | FMV_D_X_64D        => opc_OP_FP     | FLQ_32Q            => opc_LOAD_FP
  | FSQ_32Q            => opc_STORE_FP  | FMADD_RNE_Q_32Q    => opc_MADD
  | FMADD_RTZ_Q_32Q    => opc_MADD      | FMADD_RDN_Q_32Q    => opc_MADD
  | FMADD_RUP_Q_32Q    => opc_MADD      | FMADD_RMM_Q_32Q    => opc_MADD
  | FMADD_DYN_Q_32Q    => opc_MADD      | FMSUB_RNE_Q_32Q    => opc_MSUB
  | FMSUB_RTZ_Q_32Q    => opc_MSUB      | FMSUB_RDN_Q_32Q    => opc_MSUB
  | FMSUB_RUP_Q_32Q    => opc_MSUB      | FMSUB_RMM_Q_32Q    => opc_MSUB
  | FMSUB_DYN_Q_32Q    => opc_MSUB      | FNMSUB_RNE_Q_32Q   => opc_NMSUB
  | FNMSUB_RTZ_Q_32Q   => opc_NMSUB     | FNMSUB_RDN_Q_32Q   => opc_NMSUB
  | FNMSUB_RUP_Q_32Q   => opc_NMSUB     | FNMSUB_RMM_Q_32Q   => opc_NMSUB
  | FNMSUB_DYN_Q_32Q   => opc_NMSUB     | FNMADD_RNE_Q_32Q   => opc_NMADD
  | FNMADD_RTZ_Q_32Q   => opc_NMADD     | FNMADD_RDN_Q_32Q   => opc_NMADD
  | FNMADD_RUP_Q_32Q   => opc_NMADD     | FNMADD_RMM_Q_32Q   => opc_NMADD
  | FNMADD_DYN_Q_32Q   => opc_NMADD     | FADD_RNE_Q_32Q     => opc_OP_FP
  | FADD_RTZ_Q_32Q     => opc_OP_FP     | FADD_RDN_Q_32Q     => opc_OP_FP
  | FADD_RUP_Q_32Q     => opc_OP_FP     | FADD_RMM_Q_32Q     => opc_OP_FP
  | FADD_DYN_Q_32Q     => opc_OP_FP     | FSUB_RNE_Q_32Q     => opc_OP_FP
  | FSUB_RTZ_Q_32Q     => opc_OP_FP     | FSUB_RDN_Q_32Q     => opc_OP_FP
  | FSUB_RUP_Q_32Q     => opc_OP_FP     | FSUB_RMM_Q_32Q     => opc_OP_FP
  | FSUB_DYN_Q_32Q     => opc_OP_FP     | FMUL_RNE_Q_32Q     => opc_OP_FP
  | FMUL_RTZ_Q_32Q     => opc_OP_FP     | FMUL_RDN_Q_32Q     => opc_OP_FP
  | FMUL_RUP_Q_32Q     => opc_OP_FP     | FMUL_RMM_Q_32Q     => opc_OP_FP
  | FMUL_DYN_Q_32Q     => opc_OP_FP     | FDIV_RNE_Q_32Q     => opc_OP_FP
  | FDIV_RTZ_Q_32Q     => opc_OP_FP     | FDIV_RDN_Q_32Q     => opc_OP_FP
  | FDIV_RUP_Q_32Q     => opc_OP_FP     | FDIV_RMM_Q_32Q     => opc_OP_FP
  | FDIV_DYN_Q_32Q     => opc_OP_FP     | FSQRT_RNE_Q_32Q    => opc_OP_FP
  | FSQRT_RTZ_Q_32Q    => opc_OP_FP     | FSQRT_RDN_Q_32Q    => opc_OP_FP
  | FSQRT_RUP_Q_32Q    => opc_OP_FP     | FSQRT_RMM_Q_32Q    => opc_OP_FP
  | FSQRT_DYN_Q_32Q    => opc_OP_FP     | FSGNJ_Q_32Q        => opc_OP_FP
  | FSGNJN_Q_32Q       => opc_OP_FP     | FSGNJX_Q_32Q       => opc_OP_FP
  | FMIN_Q_32Q         => opc_OP_FP     | FMAX_Q_32Q         => opc_OP_FP
  | FCVT_RNE_S_Q_32Q   => opc_OP_FP     | FCVT_RTZ_S_Q_32Q   => opc_OP_FP
  | FCVT_RDN_S_Q_32Q   => opc_OP_FP     | FCVT_RUP_S_Q_32Q   => opc_OP_FP
  | FCVT_RMM_S_Q_32Q   => opc_OP_FP     | FCVT_DYN_S_Q_32Q   => opc_OP_FP
  | FCVT_RNE_Q_S_32Q   => opc_OP_FP     | FCVT_RTZ_Q_S_32Q   => opc_OP_FP
  | FCVT_RDN_Q_S_32Q   => opc_OP_FP     | FCVT_RUP_Q_S_32Q   => opc_OP_FP
  | FCVT_RMM_Q_S_32Q   => opc_OP_FP     | FCVT_DYN_Q_S_32Q   => opc_OP_FP
  | FCVT_RNE_D_Q_32Q   => opc_OP_FP     | FCVT_RTZ_D_Q_32Q   => opc_OP_FP
  | FCVT_RDN_D_Q_32Q   => opc_OP_FP     | FCVT_RUP_D_Q_32Q   => opc_OP_FP
  | FCVT_RMM_D_Q_32Q   => opc_OP_FP     | FCVT_DYN_D_Q_32Q   => opc_OP_FP
  | FCVT_RNE_Q_D_32Q   => opc_OP_FP     | FCVT_RTZ_Q_D_32Q   => opc_OP_FP
  | FCVT_RDN_Q_D_32Q   => opc_OP_FP     | FCVT_RUP_Q_D_32Q   => opc_OP_FP
  | FCVT_RMM_Q_D_32Q   => opc_OP_FP     | FCVT_DYN_Q_D_32Q   => opc_OP_FP
  | FEQ_Q_32Q          => opc_OP_FP     | FLT_Q_32Q          => opc_OP_FP
  | FLE_Q_32Q          => opc_OP_FP     | FCLASS_Q_32Q       => opc_OP_FP
  | FCVT_RNE_W_Q_32Q   => opc_OP_FP     | FCVT_RTZ_W_Q_32Q   => opc_OP_FP
  | FCVT_RDN_W_Q_32Q   => opc_OP_FP     | FCVT_RUP_W_Q_32Q   => opc_OP_FP
  | FCVT_RMM_W_Q_32Q   => opc_OP_FP     | FCVT_DYN_W_Q_32Q   => opc_OP_FP
  | FCVT_RNE_WU_Q_32Q  => opc_OP_FP     | FCVT_RTZ_WU_Q_32Q  => opc_OP_FP
  | FCVT_RDN_WU_Q_32Q  => opc_OP_FP     | FCVT_RUP_WU_Q_32Q  => opc_OP_FP
  | FCVT_RMM_WU_Q_32Q  => opc_OP_FP     | FCVT_DYN_WU_Q_32Q  => opc_OP_FP
  | FCVT_RNE_Q_W_32Q   => opc_OP_FP     | FCVT_RTZ_Q_W_32Q   => opc_OP_FP
  | FCVT_RDN_Q_W_32Q   => opc_OP_FP     | FCVT_RUP_Q_W_32Q   => opc_OP_FP
  | FCVT_RMM_Q_W_32Q   => opc_OP_FP     | FCVT_DYN_Q_W_32Q   => opc_OP_FP
  | FCVT_RNE_Q_WU_32Q  => opc_OP_FP     | FCVT_RTZ_Q_WU_32Q  => opc_OP_FP
  | FCVT_RDN_Q_WU_32Q  => opc_OP_FP     | FCVT_RUP_Q_WU_32Q  => opc_OP_FP
  | FCVT_RMM_Q_WU_32Q  => opc_OP_FP     | FCVT_DYN_Q_WU_32Q  => opc_OP_FP
  | FLQ_64Q            => opc_LOAD_FP   | FSQ_64Q            => opc_STORE_FP
  | FMADD_RNE_Q_64Q    => opc_MADD      | FMADD_RTZ_Q_64Q    => opc_MADD
  | FMADD_RDN_Q_64Q    => opc_MADD      | FMADD_RUP_Q_64Q    => opc_MADD
  | FMADD_RMM_Q_64Q    => opc_MADD      | FMADD_DYN_Q_64Q    => opc_MADD
  | FMSUB_RNE_Q_64Q    => opc_MSUB      | FMSUB_RTZ_Q_64Q    => opc_MSUB
  | FMSUB_RDN_Q_64Q    => opc_MSUB      | FMSUB_RUP_Q_64Q    => opc_MSUB
  | FMSUB_RMM_Q_64Q    => opc_MSUB      | FMSUB_DYN_Q_64Q    => opc_MSUB
  | FNMSUB_RNE_Q_64Q   => opc_NMSUB     | FNMSUB_RTZ_Q_64Q   => opc_NMSUB
  | FNMSUB_RDN_Q_64Q   => opc_NMSUB     | FNMSUB_RUP_Q_64Q   => opc_NMSUB
  | FNMSUB_RMM_Q_64Q   => opc_NMSUB     | FNMSUB_DYN_Q_64Q   => opc_NMSUB
  | FNMADD_RNE_Q_64Q   => opc_NMADD     | FNMADD_RTZ_Q_64Q   => opc_NMADD
  | FNMADD_RDN_Q_64Q   => opc_NMADD     | FNMADD_RUP_Q_64Q   => opc_NMADD
  | FNMADD_RMM_Q_64Q   => opc_NMADD     | FNMADD_DYN_Q_64Q   => opc_NMADD
  | FADD_RNE_Q_64Q     => opc_OP_FP     | FADD_RTZ_Q_64Q     => opc_OP_FP
  | FADD_RDN_Q_64Q     => opc_OP_FP     | FADD_RUP_Q_64Q     => opc_OP_FP
  | FADD_RMM_Q_64Q     => opc_OP_FP     | FADD_DYN_Q_64Q     => opc_OP_FP
  | FSUB_RNE_Q_64Q     => opc_OP_FP     | FSUB_RTZ_Q_64Q     => opc_OP_FP
  | FSUB_RDN_Q_64Q     => opc_OP_FP     | FSUB_RUP_Q_64Q     => opc_OP_FP
  | FSUB_RMM_Q_64Q     => opc_OP_FP     | FSUB_DYN_Q_64Q     => opc_OP_FP
  | FMUL_RNE_Q_64Q     => opc_OP_FP     | FMUL_RTZ_Q_64Q     => opc_OP_FP
  | FMUL_RDN_Q_64Q     => opc_OP_FP     | FMUL_RUP_Q_64Q     => opc_OP_FP
  | FMUL_RMM_Q_64Q     => opc_OP_FP     | FMUL_DYN_Q_64Q     => opc_OP_FP
  | FDIV_RNE_Q_64Q     => opc_OP_FP     | FDIV_RTZ_Q_64Q     => opc_OP_FP
  | FDIV_RDN_Q_64Q     => opc_OP_FP     | FDIV_RUP_Q_64Q     => opc_OP_FP
  | FDIV_RMM_Q_64Q     => opc_OP_FP     | FDIV_DYN_Q_64Q     => opc_OP_FP
  | FSQRT_RNE_Q_64Q    => opc_OP_FP     | FSQRT_RTZ_Q_64Q    => opc_OP_FP
  | FSQRT_RDN_Q_64Q    => opc_OP_FP     | FSQRT_RUP_Q_64Q    => opc_OP_FP
  | FSQRT_RMM_Q_64Q    => opc_OP_FP     | FSQRT_DYN_Q_64Q    => opc_OP_FP
  | FSGNJ_Q_64Q        => opc_OP_FP     | FSGNJN_Q_64Q       => opc_OP_FP
  | FSGNJX_Q_64Q       => opc_OP_FP     | FMIN_Q_64Q         => opc_OP_FP
  | FMAX_Q_64Q         => opc_OP_FP     | FCVT_RNE_S_Q_64Q   => opc_OP_FP
  | FCVT_RTZ_S_Q_64Q   => opc_OP_FP     | FCVT_RDN_S_Q_64Q   => opc_OP_FP
  | FCVT_RUP_S_Q_64Q   => opc_OP_FP     | FCVT_RMM_S_Q_64Q   => opc_OP_FP
  | FCVT_DYN_S_Q_64Q   => opc_OP_FP     | FCVT_RNE_Q_S_64Q   => opc_OP_FP
  | FCVT_RTZ_Q_S_64Q   => opc_OP_FP     | FCVT_RDN_Q_S_64Q   => opc_OP_FP
  | FCVT_RUP_Q_S_64Q   => opc_OP_FP     | FCVT_RMM_Q_S_64Q   => opc_OP_FP
  | FCVT_DYN_Q_S_64Q   => opc_OP_FP     | FCVT_RNE_D_Q_64Q   => opc_OP_FP
  | FCVT_RTZ_D_Q_64Q   => opc_OP_FP     | FCVT_RDN_D_Q_64Q   => opc_OP_FP
  | FCVT_RUP_D_Q_64Q   => opc_OP_FP     | FCVT_RMM_D_Q_64Q   => opc_OP_FP
  | FCVT_DYN_D_Q_64Q   => opc_OP_FP     | FCVT_RNE_Q_D_64Q   => opc_OP_FP
  | FCVT_RTZ_Q_D_64Q   => opc_OP_FP     | FCVT_RDN_Q_D_64Q   => opc_OP_FP
  | FCVT_RUP_Q_D_64Q   => opc_OP_FP     | FCVT_RMM_Q_D_64Q   => opc_OP_FP
  | FCVT_DYN_Q_D_64Q   => opc_OP_FP     | FEQ_Q_64Q          => opc_OP_FP
  | FLT_Q_64Q          => opc_OP_FP     | FLE_Q_64Q          => opc_OP_FP
  | FCLASS_Q_64Q       => opc_OP_FP     | FCVT_RNE_W_Q_64Q   => opc_OP_FP
  | FCVT_RTZ_W_Q_64Q   => opc_OP_FP     | FCVT_RDN_W_Q_64Q   => opc_OP_FP
  | FCVT_RUP_W_Q_64Q   => opc_OP_FP     | FCVT_RMM_W_Q_64Q   => opc_OP_FP
  | FCVT_DYN_W_Q_64Q   => opc_OP_FP     | FCVT_RNE_WU_Q_64Q  => opc_OP_FP
  | FCVT_RTZ_WU_Q_64Q  => opc_OP_FP     | FCVT_RDN_WU_Q_64Q  => opc_OP_FP
  | FCVT_RUP_WU_Q_64Q  => opc_OP_FP     | FCVT_RMM_WU_Q_64Q  => opc_OP_FP
  | FCVT_DYN_WU_Q_64Q  => opc_OP_FP     | FCVT_RNE_Q_W_64Q   => opc_OP_FP
  | FCVT_RTZ_Q_W_64Q   => opc_OP_FP     | FCVT_RDN_Q_W_64Q   => opc_OP_FP
  | FCVT_RUP_Q_W_64Q   => opc_OP_FP     | FCVT_RMM_Q_W_64Q   => opc_OP_FP
  | FCVT_DYN_Q_W_64Q   => opc_OP_FP     | FCVT_RNE_Q_WU_64Q  => opc_OP_FP
  | FCVT_RTZ_Q_WU_64Q  => opc_OP_FP     | FCVT_RDN_Q_WU_64Q  => opc_OP_FP
  | FCVT_RUP_Q_WU_64Q  => opc_OP_FP     | FCVT_RMM_Q_WU_64Q  => opc_OP_FP
  | FCVT_DYN_Q_WU_64Q  => opc_OP_FP     | FCVT_RNE_L_Q_64Q   => opc_OP_FP
  | FCVT_RTZ_L_Q_64Q   => opc_OP_FP     | FCVT_RDN_L_Q_64Q   => opc_OP_FP
  | FCVT_RUP_L_Q_64Q   => opc_OP_FP     | FCVT_RMM_L_Q_64Q   => opc_OP_FP
  | FCVT_DYN_L_Q_64Q   => opc_OP_FP     | FCVT_RNE_LU_Q_64Q  => opc_OP_FP
  | FCVT_RTZ_LU_Q_64Q  => opc_OP_FP     | FCVT_RDN_LU_Q_64Q  => opc_OP_FP
  | FCVT_RUP_LU_Q_64Q  => opc_OP_FP     | FCVT_RMM_LU_Q_64Q  => opc_OP_FP
  | FCVT_DYN_LU_Q_64Q  => opc_OP_FP     | FCVT_RNE_Q_L_64Q   => opc_OP_FP
  | FCVT_RTZ_Q_L_64Q   => opc_OP_FP     | FCVT_RDN_Q_L_64Q   => opc_OP_FP
  | FCVT_RUP_Q_L_64Q   => opc_OP_FP     | FCVT_RMM_Q_L_64Q   => opc_OP_FP
  | FCVT_DYN_Q_L_64Q   => opc_OP_FP     | FCVT_RNE_Q_LU_64Q  => opc_OP_FP
  | FCVT_RTZ_Q_LU_64Q  => opc_OP_FP     | FCVT_RDN_Q_LU_64Q  => opc_OP_FP
  | FCVT_RUP_Q_LU_64Q  => opc_OP_FP     | FCVT_RMM_Q_LU_64Q  => opc_OP_FP
  | FCVT_DYN_Q_LU_64Q  => opc_OP_FP
  end.
